### ISSUE TITLE
Support for input stream as return type for @Attachment methods

### ISSUE THREAD

**Issue by volkovs** [allure-framework/allure1#412]
Test may generate huge log, which should be attached to test. Currently it is possible only by byte[] and java.lang.String loading full content into memory.
(Input stream should be closed by framework.)

**Comment by baev** [comment]
@buzdin `java.io.File` - nope, I would not like to copy it, handle errors etc. `java.net.URI` sounds good could you please submit us the pull request?

**Comment by sskorol** [comment]
@baev @buzdin adding attachment's `URI` return type will affect core.

However, there're 2 ways to workaround it without core modification:
 - Leave it to user, who will return his own html attachment with required links. :)
 - Tweak `allure-report-face` a bit to support such things with pure `String` return type. I could create a PR as soon as [#738](https://github.com/allure-framework/allure-core/pull/738) is merged.

**Comment by baev** [comment]
Done in new Java commons https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/Allure.java#L157
