### ISSUE TITLE
Capture test log output and store as attachment

### ISSUE THREAD

**Issue by buzdin** [allure-framework/allure1#420]
For some tests it is important to capture the output of the test case logs and attach to the report. This can be correlated with test step break down, so it would be visible what test log part is belonging to which test step.

This could be implemented as attachments or as a separate feature.

Technically it could be either logger API implementation or hooking on System.out level and replacing the writer. Not sure about non-Java frameworks.

**Comment by brbrr** [comment]
Any update on that issue so far?

**Comment by RocketRaccoon** [comment]
Could you provide 'test log per test step' feature implementation example?

**Comment by baev** [comment]
moved to https://github.com/allure-framework/allure-java/issues/18
