### ISSUE TITLE
Abilty to add parameters to step

### ISSUE THREAD

**Issue by r-coder** [allure-framework/allure1#486]
I'm using allure-java-adaptor-api for gathering information about tests being running in Robot Framework. 

I have steps added for every scenario's keyword in my report. Most keywords contains number of arguments. I have to list arguments in step title label. Looks not very good for me. Of course, I can use step attachments for arguments listing. But its looks like some kind of overkill. 

Is it possible to add parameters to steps like it can be done for test cases? If not, have you any plans to implement extra labels for step?

**Comment by baev** [comment]
@r-coder thanks for suggestion!

> Is it possible to add parameters to steps like it can be done for test cases?

Nope, only using title =(

> If not, have you any plans to implement extra labels for step?

Yep, in the future we plan to implement such feature.

**Comment by buzdin** [comment]
+1 on our backlog as well

**Comment by baev** [comment]
Almost done in allure2. See https://github.com/allure-framework/allure2/issues/93
