### ISSUE TITLE
Messed Up CSV Preview

### ISSUE THREAD

**Issue by sharadJay** [allure-framework/allure1#547]
Hi , I am currently trying to attach a csv file into my reports and I observed although csv with less columns are shown correctly but csv with higher number of columns are messed up on preview page. This is how preview looks with 24 columns in csv :
![csv preview](http://s23.postimg.org/vq38u78kr/csv.png)

Please look into it

**Comment by VikomiC** [comment]
Need to replace current table.

UI Grid could be used instead of table.
http://ui-grid.info/docs/#/tutorial/191_horizontal_scrolling

Only a question, how to hide header. I didn't found it.

**Comment by just-boris** [comment]
@automationNinja what the expected result in your case? Do you want to see horizotal scroll?

**Comment by automationNinja** [comment]
Considering that table has large number of columns, It should have provided view in horizontal column.  Even if the table could be re-sized according to preview window, it will be fine.

**Comment by baev** [comment]
Could some noble gentlemens help us with such problem and send us the pull request?
Summon @allure-framework/jvm-developers @allure-framework/qatools-team

**Comment by clicman** [comment]
Don't see the final decision how it should looks. Horizontal scroll on preview sounds bad 🙅

**Comment by baev** [comment]
@clicman there is few problems:

1) Excel files sometimes uses different delimiter - we should add ability to provide delimiter in mime-type prefix.
2) Huge csv - I don't see any except horizontal =(

**Comment by baev** [comment]
please check out Allure 2. Feel free to reopen the issue if the problem still exists
