### ISSUE TITLE
Add capability to accept multiple test suites per XML file

### ISSUE THREAD

**Issue by ericson-cepeda** [allure-framework/allure1#558]
Using Gulp + Jasmine reporters (https://github.com/larrymyers/jasmine-reporters) deliver files like:

```
<testsuites>
  <ns2:test-suite xmlns:ns2="urn:model.allure.qatools.yandex.ru"  start="1429678415245" stop="1429678415247">
    <name>Conversation</name>
    <test-cases>
      <test-case start="1429678415245" stop="1429678415246" status="passed">
        <name>Conversation authorized on /</name>
      </test-case>
    </test-cases>
  </ns2:test-suite>
</testsuites>
```

How about adding ns2:test-suites?

**Comment by just-boris** [comment]
We are using multiple suite files to process them in parallel.
Why do you want single file. JUnit-reporter can generate file per suite, so this is not a big deal

**Comment by baev** [comment]
@ericson-cepeda we are going to remove suites from model, and provide all information about suites using labels. After it done you can provide one xml for each test case or one xml for some test case group (as you wish). I guess it covers your case

**Comment by ericson-cepeda** [comment]
+1, I will be aware of it. Thank you.

**Comment by baev** [comment]
Probably allure2 model will support such feature. See https://github.com/allure-framework/allure2-model/issues/8
