### ISSUE TITLE
Exception in TestNG tearDown() method doesn't fail the test

### ISSUE THREAD

**Issue by volkovs** [allure-framework/allure1#569]
Allure version used: 1.4.12
Test Framework: TestNG

There are several issues with test configuration methods, but I guess they all are related to each other.
Might be also related to #517 discussion.

So, we have following Test:

``` java
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;
import ru.yandex.qatools.allure.annotations.Step;

public class CanceledTest {

    private static int counter = 0;

    @BeforeMethod
    public void setUp() {
        setUpStep1();
        setUpStep2();
    }

    @AfterMethod
    public void tearDown() {
        tearDownStep1();
        tearDownStep2();
        tearDownStep3();
    }

    @Test
    public void canceled1() {
        testMethodStep1();
        testMethodStep2();
    }

    @Test
    public void canceled2() {
        testMethodStep1();
        testMethodStep2();
    }

    @Test
    public void canceled3() {
        testMethodStep1();
        testMethodStep2();
    }

    @Step
    private void setUpStep1() {
        // do nothing
    }

    @Step
    private void setUpStep2() {
        // do nothing
    }

    @Step
    private void tearDownStep1() {
        // do nothing
    }

    @Step
    private void tearDownStep2() {
        // do nothing
    }

    @Step
    private void testMethodStep1() {
        // do nothing
    }

    @Step
    private void testMethodStep2() {
        // do nothing
    }

    @Step
    private void tearDownStep3() {
        if (++counter == 3) {
            throw new RuntimeException("Test clean up failed");
        }
    }

}
```

Each configuration / test method calls according test steps. In the last test tearDown() method fails.
## Issues

1 Tear down steps missing:

![image](https://cloud.githubusercontent.com/assets/743546/7514905/aeeb485e-f4ca-11e4-9c17-3d7d2afb7a46.png)

2 Tear down steps out of order:

![image](https://cloud.githubusercontent.com/assets/743546/7514922/e413ca92-f4ca-11e4-98c4-4b9768655d35.png)

3 Tear down step 3 should be BROKEN (currently PASSED):

![image](https://cloud.githubusercontent.com/assets/743546/7514937/13733fd4-f4cb-11e4-8bf6-c47460532fa4.png)

4 Canceled 3 test case shouldn't be PASSED:

![image](https://cloud.githubusercontent.com/assets/743546/7514957/36f2edce-f4cb-11e4-999e-5fa2bbefad2e.png)

5 Defects tab shouldn't show "No defects in test run. Good job!":

![image](https://cloud.githubusercontent.com/assets/743546/7514974/57df6634-f4cb-11e4-8e54-0dadf0ddd5a2.png)

**Comment by baev** [comment]
@volkovs thanks for the report. 

It's problem of the TestNG adaptor. We are using `ITestListener` and `onTestSuccess`, `onTestFailure`, `onTestFailedButWithinSuccessPercentage` and `onTestSkipped` methods to mark a test as finished. But TestNG call the methods **before** @AfterMethod.

I don't know is there a way to handle fixtures (maybe we can use other listener, an example `IInvokedMethodListener`). You can investigate this problem and send us a pull request.

**Comment by braimanm** [comment]
@baev In TestNG adapter the following methods: onConfigurationSuccess, onConfigurationFailure and . onConfigurationSkip are used for all TestNG configuration methods which are all the flavours of Before and After methods.

**Comment by braimanm** [comment]
@volkovs  the behavior is correct, you have 3 tests which suppose to pass, tearDown is not part of the test and it executes after the test. If you run your example using TestNg you will get the following result:
===============================================
    Default test
    Tests run: 3, Failures: 0, Skips: 0
    Configuration Failures: 1, Skips: 0
=============================================== 
And this is almost the same result as you are getting the only difference is that last execution of tearDown should fail instead of canceled.  Your setUp and tearDown methods includes steps which shown by Allure as part of the test and they should not be part of the test as they suppose to be independent methods which setup your environment before the test and cleans environment after your test.

**Comment by volkovs** [comment]
@braimanm Good point. Nevertheless test execution / maven build is failed.

@baev @eroshenkoam 
Guys, after extensive usage of Allure with Test NG we received feedback. The most confusing part of the report is displaying test / suite configuration methods. Reports are reviewed by (top) management and clients, not only by QA and developers. So it becomes even more challenging to make report straightforward for non-technical people.

I would like to describe some issues. And then I would like to agree on what is ideal solution that solves mentioned issues. Then we could discuss possible (or impossible) pull requests.

So the issues are following:
- suite configuration failure **corrupts test execution time** and timeline (should be a bug straightforward to fix)
- artificial test cases / suites are **created only on configuration method failure** (we would like to see them always, so clients get used to the structure and know "explicitly" that their `setUp()` worked successfully)
- artificial test cases / suites **don't link back to** test case / suite, which **cause**d the problem, e.g. having multiple suites (and suite configuration failure) it is not clear which one had a problem triggering artificial suite ‘Unknown test suite’.

We would suggest to move test configuration failure details from artificial test to test step (now test steps can have their own statuses). Also to move suite configuration failure details from artificial suite to artificial test. By thus we will see original test or suite causing the issue.
Following tables represent what statuses test cases and steps have in different scenarios using different test configuration method annotations (TestNG):
 

`@BeforeMethod` / `@AfterMethod`

|**STEP name**          |Step status         |Test status|
|--------------------------|---------------------|----------------|
|beforeMethod |passed||
|test                        |passed||
|afterMethod     |passed||
|                                                                ||PASSED|
|---------------------|---------------------------|-------------------------------|
|beforeMethod |broken||
|test                 | cancel||
|afterMethod     |cancel||
|                                                               || CANCEL|
|------------------|----------------------------|---------------------------------|
|beforeMethod |passed||
|test                        |broken||
|afterMethod     |passed||
|||                                                                BROKEN|
|-----------------------|------------------------------|--------------------------|
|beforeMethod| passed||
|test                     |   passed||
|afterMethod    | broken||
|||             BROKEN (or PASSED?)|

 
 
 
`@BeforeClass` / `@AfterClass`

|**STEP name**          |Step status         |Test status|
|---------------------|-------------------------|-----------------------|
|beforeClass        |passed|
|test1                      |passed|
|||                                                                PASSED|
|test2                      |passed|
|afterClass            |passed|
|||                                                                PASSED|
|---------------------|---------------------|---------------|
|beforeClass        |passed
|test1                      |broken
|||                                                                BROKEN |
|test2                      |passed
|afterClass            |passed
|||                                                                PASSED|
|-----------------------|--------------------|--------------|
|beforeClass        |broken
|test1                      |cancel
|||                                                                CANCEL |
|test2                      |cancel
|afterClass            |cancel
|||                                                                CANCEL|
|----------------------|----------------|-------------------|
|beforeClass        |passed||
|test1                      |passed||
|||                                                                PASSED|
|test2                      |passed||
|afterClass            |broken||
|||                                                                BROKEN (or PASSED?)|
|-----------------------|------------------|----------------|
|beforeClass        |passed||
|test1                      |passed||
|||                                                                PASSED|
|test2                      |broken||
|afterClass            |passed||
|||                                                                BROKEN|

 
 
 
`@BeforeSuite` / `@AfterSuite`

|**TEST name**        |  Step status         |Test status|
|-----------------|---------------------|--------------------------|
|beforeSuite       | passed
|||                                                                PASSED
|test1                    |  passed
|||                                                                PASSED
|test2                    |  passed  
|||                                                                PASSED
|afterSuite          |  passed
|||                                                                PASSED
|-------------------|-------------------|-------------------|
|beforeSuite        |broken
|||                                                                BROKEN 
|test1                      |cancel
|||                                                                CANCEL 
|test2                      |cancel
|||                                                                CANCEL 
|afterSuite            |cancel
|||                                                                CANCEL
|----------------------|-------------------|----------------
|beforeSuite        |passed
|||                                                                PASSED
|test1                      |broken
|||                                                                BROKEN
|test2                      |passed  
|||                                                                PASSED 
|afterSuite            |passed
|||                                                                PASSED
|---------------------|-------------------|-----------------
|beforeSuite        |passed
|||                                                                PASSED
|test1                      |passed
|||                                                                PASSED 
|test2                      |passed  
|||                                                                PASSED 
|afterSuite            |broken
|||                                                                BROKEN

 
 
Please note that `@Before/@AfterMethod` and `@Before/@AfterClass` failure creates artificial test steps. `@Before/@AfterSuite` - artificial test case.
 
Could you please review the tables and comment back if you see it the same? Once we agree on that we can start investigation if that could be implemented at all (taking into account TestNG events complexity).

**Comment by braimanm** [comment]
Your matrix should have all possible scenarios, what if you have beforeSuite, beforeClass, beforeMethod and all other variation of testNg's after configuration methods in one single class?
 
 If you choose TestNg as your primary unit-testing framework then you bound to the rules of testNG, unfortunately Allure is not designed specifically for testNg and it follows standard xUnit notations.
 
 TestNg keeps results separately between tests and configuration methods and it shows results in following manner 
'===============================================
    Default test
    Tests run: 3, Failures: 0, Skips: 0
    Configuration Failures: 1, Skips: 0
==============================================='
Now looking at this result it’s not clear if test passed or test failed there are two interpretations: one can say I don’t care if the teardown (or configuration after method in testNg jargon) is failed as long as my test is passed and the other can say the test should fail as I should be notified that any executed method in my test is failing. Cédric Beust creator of testNg made a decision when he introduced TestNg Eclipse plug-in to fail the test if test or one of its many flavours of before and after configuration methods is failed, but in the same time if you look at generated by TesNg HTML report this test is PASSED.  Another decision Cédric made in his Eclipse plug-in is to show the configuration methods only in case they are skipped or failed.
 
Now it’s possible to take all the Cédric ideas which he implemented in his TestNg Eclipse plug-in and implement them in the Allure,

**Comment by volkovs** [comment]
Hi @braimanm

> Your matrix should have all possible scenarios

Yes, there might be tricky cases if combination of methods fail, but I haven't found any (please correct me if I am wrong). Every combination looks straightforward:
1. Suite level methods are orthogonal to test class/method level configuration methods (since they go to separate tests in report). The only affect is when `@BeforeSuite` fails and cancels the tests. But in this way other configuration methods are canceled as well (and don't affect tests statuses).
2. Let's consider `@BeforeMethod` / `@AfterMethod` and `@BeforeClass / @AfterClass` interference:

|STEP name	|Step status	|Test status
|---------------|---------------|-----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|passed
|afterClass	|passed
|||				PASSED
|---------------|----------------|----------------
|beforeClass	|broken / failed
|beforeMethod	|cancel
|test		|cancel
|afterMethod	|cancel
|afterClass	|cancel
|||				CANCEL
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|broken / failed
|test		|cancel
|afterMethod	|cancel
|afterClass	|passed
|||				CANCEL
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|broken / failed
|afterMethod	|passed
|afterClass	|passed
|||				BROKEN / FAILED
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|broken / failed
|afterClass	|passed
|||				BROKEN / FAILED
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|broken
|afterClass	|broken
|||				BROKEN
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|failed
|afterClass	|failed
|||				FAILED
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|broken
|afterClass	|failed
|||				BROKEN or FAILED
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|failed
|afterClass	|broken
|||				FAILED or BROKEN
|---------------|----------------|----------------
|beforeClass	|passed
|beforeMethod	|passed
|test		|passed
|afterMethod	|passed
|afterClass	|broken / failed
|||				BROKEN / FAILED

Some comments on the matrix above:
 - If afterMethod and afterClass have different statuses (broken and failed) whatever status is taken for test. IMO this is not so important as seeing that particular test configuration method fails.
 - If some test method is marked as ignored or disabled its status is PENDING. IMO BROKEN or FAILED statuses (from failed configuration methods) should override PENDING as being higher severity.
 - Please note that test steps have their own statuses visible in report (so if test fails you will see exactly what configuration method failed, what passed/executed, and what was canceled)

> ...and all other variation of testNg's after configuration methods

TestNG has one more configuration annotation `@BeforeTest` / `@AfterTest` for wrapping tests defined in XML. The same logics below could be applied for these annotations.

> unfortunately Allure is not designed specifically for testNg and it follows standard xUnit notations

That is fine. So, we agree that there is no full match between TestNG and Allure, so we don't expect Allure to report all the tests exactly as they are reported by TestNG Eclipse plugin, do we? I think that is an advantage of Allure - developers can switch test framework behind and Allure users won't even notice that.

> Cédric Beust made a decision... to fail the test if test or one of its many flavours of before and after configuration methods is failed, but in the same time if you look at generated by TesNg HTML report this test is PASSED.
> Another decision Cédric made in his Eclipse plug-in is to show the configuration methods only in case they are skipped or failed.

Allure is test framework agnostic tool. That is why I don't think it should look back at TestNG reporting. Moreover non-technical managers and clients don't usually use TestNG Eclipse plugin, but they do use Allure! So, my point is that requirements to TestNG and Allure reports are different.
(I would suggest that the configuration methods should always be visible in the allure report (some people may disagree here), that way people are sure they are not missing any information.)

>Now it’s possible to take all the Cédric ideas which he implemented in his TestNg Eclipse plug-in and implement them in the Allure.

Thanks for suggestion to review Eclipse TestNG plugin. I will look for ideas and inspiration there.

What do you think? Does it still sound like ad hoc solution?


br,
Mihail

**Comment by braimanm** [comment]
The only TestNg oriented reporting tool that I familiar with (accept Allure) is TestNg Eclipse plug-in and here how it represents results:

First let’s understand the execution order of TestNg suite. The suite execution is as follows (in case all the configuration methods exist in test class):

    1.	@BeforSuite  (if exists)
    2.	@BeforeTest (if exists)
    3.	@BeforeClass (if exists)
    4.	@BeforeMethod (if exists)
    5.	@Test
    6.	@AfterMethod (if exists)
    7.	@AfterClass (if exists)
    8.	@AfterTest (if exists)
    9.	@AfterSuite (if exists)

If all the configuration methods will pass then Eclipse plug-in will show only the results of methods with Test annotation, but if one of the configuration methods will fail then all the methods which follows the failed configuration method according to the execution order will be marked as skipped (cancelled). 
Here are several examples:

If BeforeSuite fails then the following results will be presented in the report:

    1.	@BeforSuite  - FAILED
    2.	@BeforeTest  - SKIPPED
    3.	@BeforeClass  - SKIPPED
    4.	@BeforeMethod  - SKIPPED
    5.	@Test - SKIPPED
    6.	@AfterMethod - SKIPPED
    7.	@AfterClass - SKIPPED
    8.	@AfterTest - SKIPPED
    9.	@AfterSuite - SKIPPED

If BeforeMethod fails then the following results will be presented in the report:

    1.	@BeforeMethod  - FAILED
    2.	@Test - SKIPPED
    3.	@AfterMethod - SKIPPED
    4.	@AfterClass - SKIPPED
    5.	@AfterTest - SKIPPED
    6.	@AfterSuite - SKIPPED

If AfterClass fails then the following results will be presented in the report:

    1.	@Test – PASSED or FAILED  (depends on the test result)
    2.	@AfterClass - FAILED
    3.	@AfterTest - SKIPPED
    4.	@AfterSuite - SKIPPED

**Comment by PavelSusloparovNYT** [comment]
Hi! 
Any updates here? 
It's great to have this

```
1.  @BeforeMethod  - FAILED
2.  @Test - SKIPPED
3.  @AfterMethod - SKIPPED
4.  @AfterClass - SKIPPED
5.  @AfterTest - SKIPPED
6.  @AfterSuite - SKIPPED
```

**Comment by baev** [comment]
should be fixed in new TestNG adaptor https://github.com/allure-framework/allure-java

**Comment by ilusi0npl** [comment]
Issues still occurs on Allure 2.8.1 and TestNG 6.14.3

**Comment by baev** [comment]
@ilusi0npl please do not comment on closed issues, create a new one instead
