### ISSUE TITLE
Mixed steps suites if before starting the suites is called single step (used TestNG).

### ISSUE THREAD

**Issue by smaxim84** [allure-framework/allure1#570]
We have two suites, which cause one test (one class)

``` java
import org.testng.TestNG;
import org.testng.xml.XmlClass;
import org.testng.xml.XmlSuite;
import org.testng.xml.XmlTest;
import ru.yandex.qatools.allure.Allure;
import ru.yandex.qatools.allure.annotations.Step;
import ru.yandex.qatools.allure.events.ClearStepStorageEvent;

import java.util.ArrayList;
import java.util.List;

public class RunTests {

    private XmlTest buildXmlTest(XmlSuite xmlSuite, String xmlTestName){
        List<XmlClass> xmlClasses = new ArrayList<>();
        xmlClasses.add(new XmlClass(SimpleTest1.class));

        XmlTest xmlTest = new XmlTest(xmlSuite);
        xmlTest.setName(xmlTestName);
        xmlTest.setXmlClasses(xmlClasses);
        return xmlTest;
    }

    private XmlSuite buildSuite(String suiteName, String testName){
        XmlSuite xmlSuite = new XmlSuite();
        xmlSuite.setName(suiteName);
        buildXmlTest(xmlSuite, testName);
        return xmlSuite;
    }

    private void runTestNg(){

        final TestNG testNG = new TestNG(false);
        List<XmlSuite> suites = new ArrayList<>();
        suites.add(buildSuite("Suite 1", "Test 1"));
        suites.add(buildSuite("Suite 2", "Тест 2"));

        testNG.setXmlSuites(suites);
        testNG.setSuiteThreadPoolSize(2);
        testNG.run();
    }


    public static void main(String[] args) {
        RunTests runTests = new RunTests();

        // this step will be to mix other steps in suites, It is seen in the Allure report.
        runTests.badStep();

        // if uncomment - it will save the situation
        //Allure.LIFECYCLE.fire(new ClearStepStorageEvent());

        runTests.runTestNg();
    }

    @Step("Bad Step!!!")
    private static void badStep(){

    }
}
```

``` java
public class SimpleTest1 extends Assert {

    @Test(description = "Simple test 1")
    @Title("Simple test 1")
    public void MyTest(){
        firstStep();
    }

    @Step("Simple test 1 - FirstStep 1")
    public void firstStep(){
    }
}
```

After running and generation Allure report we see dublicates steps in this suites:

![screen](https://cloud.githubusercontent.com/assets/12294642/7515715/135fb9c6-f4d2-11e4-99d8-fd4147e40a2e.png)

If we don't call badStep or use ClearStepStorageEvent() before run suites - then all is well:

![screen2](https://cloud.githubusercontent.com/assets/12294642/7515974/60d66c34-f4d4-11e4-868d-c823402f7e3e.png)

Why:
1) "Bad Step!!!" added to each suite?
2) does the same test steps are summed in suites?

**Comment by baev** [comment]
@smaxim84 thanks for the report.

In two words - it is doesn't work like this. What behavior are you expect?

**Comment by smaxim84** [comment]
Main:
I expect that the test steps of the two suites will not mixed.
Optional: 
that the bad step is added to the first suite.

**Comment by baev** [comment]
> that the bad step is added to the first suite.

Why only first? Seems like we should add it to both suites

**Comment by pozharko** [comment]
Well, this step was executed before both suites started. I expect, that badStap won`t be added to any suite.

**Comment by smaxim84** [comment]
> Well, this step was executed before both suites started. I expect, that badStap won`t be added to any suite.

Ok! I agree with @pozharko

**Comment by baev** [comment]
@smaxim84 sorry for the delay

I got it. Lets clear steps storage at **test case started** events. I guess it is should not break anything.

**Comment by baev** [comment]
@smaxim84 @pozharko could someone please send the PR?

**Comment by baev** [comment]
should be fixed in new TestNg adaptor https://github.com/allure-framework/allure-java
