### ISSUE TITLE
It is necessary to divide the test cases and tests in the report (TestNG)

### ISSUE THREAD

**Issue by LooMaclin** [allure-framework/allure1#580]
It is necessary to divide the test cases and tests in the report, so the report will be visually closer to the ideology of the xUnit and the file structure, run tests TestNG.CML. In the current implementation, test cases and call them tests are mixed together. I suggest the following variant of report (TestNG) tab in the xUnit:
- 0 level: test cases;
- Level 1: tests which were performed in a particular test case;
- Level 2: the test methods are invoked in a particular test.

This desire is due to the fact that when running many test cases, the report is very difficult to find and to determine where and what was called in the test case.

Here is an example when it is difficult to understand the report:

![1](https://cloud.githubusercontent.com/assets/10957765/7897957/01a13c42-070a-11e5-9a6f-14981f6f97a7.png)

Here's an example of what I would like to see, when the structure testng.xml corresponds to the display in the report:

![3](https://cloud.githubusercontent.com/assets/10957765/7898008/f013879e-070b-11e5-8f6a-73e3fda10848.png)

**Comment by buzdin** [comment]
Allure has test steps concept. Do you think that some of your levels map to test steps?

**Comment by baev** [comment]
@buzdin I personally like to create a new tab for testNg with such grouping. What are you think?
IMHO separate test methods using steps - bad idea. At least while test case can contains only one failure.

**Comment by braimanm** [comment]
By default when you’re using maven surefire plugin with the default configuration, TestNg is setup as standard xUnit framework. The suite name and test name is generated automatically by surefire plugin.  TestNg is using XML Suite file as an input for execution and orchestration of tests. Some test execution frameworks like Maven surefire or any IDE testNg plugins area generating the TestNG XML Suite file before the test execution and creating an illusion that your test classes are the one which are executed.
But when you provide your own TestNg Xml Suite file you can configure the test to be executed in very different and unpredictable fashion.  To fully implement all the features of TestNg test component hierarchy you have to implement support for the following containers:
•	Suites of suite files
•	Suites of Tests 
•	Tests
•	Groups
•	Test cases (methods)
•	Test case invocations  (multiple instance invocation of the same test)
•	and the last one: Allure steps

**Comment by baev** [comment]
Done in new TestNG adaptor. https://github.com/allure-framework/allure-java

<img width="467" alt="screen shot 2017-03-01 at 16 31 15" src="https://cloud.githubusercontent.com/assets/2149631/23461820/83fce980-fe9c-11e6-8542-7a1cc92e12a8.png">
