### ISSUE TITLE
Tests with failures in both test method and cleanup method report only the cleanup failure.

### ISSUE THREAD

**Issue by dsafar** [allure-framework/allure1#593]
We're running our test cases with JUnit and using the @Before and @After annotations to do setup and cleanup.  When a test fails in setup or the test method, it will sometimes ALSO fail in cleanup.  One of the things we like about Allure is that it reports these double-failed tests as only a single failed test, maintaining the accuracy of the failure count.

However, recently we've noticed that the one failure that is being reported is the failure in the cleanup method -- the LAST failure, not the first one.  It would be strongly preferable to report the first failure, as it is likely the cause of the second one.

**Comment by baev** [comment]
@dsafar thanks for suggesting! 

I afraid there is a few different opinions about this problem. Someone think that only last failure is important because it finally fail the test (an example - you can catch first failure and continue the test execution), but other people think that first failure more import because it is the reason of other failures. 

I personally like your proposition - IMHO each test should contains only one failure (and maybe few cleanup unimportant failures).

Any ideas how we can solve the problem and don't break other people?

**Comment by dsafar** [comment]
IMO failures in setup or cleanup are different from failures in test methods, and I would prefer to see them reported differently.

Interaction with the functionality under test should all be contained in the test method, which means that a failure in the setup method doesn't actually mean the test failed -- rather, the test couldn't even be executed, because some *other* functionality that was prerequisite to it failed.  There should be a different test case testing that prerequisite functionality, which we would expect to be failing in its test method because of this defect.

Similarly, if the setup and the test method pass, but a failure occurs in cleanup, then the functionality under test is working fine -- technically, the test passed, but some other functionality necessary to return the environment to its default state is broken.  Again, I would expect to see another test case testing this functionality specifically and failing.

That may be a bit much to ask for -- it's a fundamental shift in how we view what "passing" and "failing" mean and I'm not aware of a reporting tool that actually does it that way.  Some thoughts on this, assuming the technical challenge of detecting and differentiating the two failures is minimal and this is really a question of deciding what the right thing to do is:

I see two main options here to satisfy my request and the needs of other users who prefer it the way it is:

1) Let the user decide.  This could be controlled by a setting (report first failure vs. report last failure) in the pom file or passed in by Jenkins (or equivalent for users who aren't using Maven/Jenkins).

2) Report both, but only count one.  For instance, when I click through from the summary to the testsuite to the test case, perhaps the test case panel would have two red boxes with stack trace buttons on it instead of one -- either setup and cleanup or the test method and cleanup.  The two should be listed in the order they occurred and clearly labeled so we can tell whether the first one is from the setup method or the test method.  As I mentioned above, knowing whether the test method itself failed is important to knowing whether the failure indicates that the functionality under test is broken or something else is broken.

Between the two, I think reporting both is preferable (although the two are not mutually exclusive; the setting could offer values of "first", "last", or "both").  It would show me at a glance both errors/exceptions generated by the test case and let me decide which one is more important, and also what kind of issue it may have caused later in the test so I can think about whether that's okay or whether additional work is needed to ensure that cleanup doesn't experience that kind of issue when a previous method fails in that way.

**Comment by marty30** [comment]
I would love to see the second idea. We are using the clean-up also for checks that should be done after each test (like checking if the application does not show an error). Currently these exceptions are shown nicely in JUnit and Allure. But this exception overrides the error that was thrown by the test itself.

**Comment by baev** [comment]
check out brand new TestNG adaptor https://github.com/allure-framework/allure-java
