### ISSUE TITLE
Proposed changes to Allure report framework for better TestNG support

### ISSUE THREAD

**Issue by braimanm** [allure-framework/allure1#610]
1. Option to add a message as a reason to TestCaseCanceledEvent instead of exception. There are no exceptions in skipped configuration and test methods, those methods are never executed by TestNg so there is no way they can throw exceptions, 
2. Decorate configuration methods with textual effects like bold\italic fonts or in different color 
3. In the Test suites area of the Allure report show TestNg suites and tests as a tree were each node of the tree is a Suite tag and child of a node is a Test tag (This will fix issue #580). This will require to change Allure model to have suites and subsuites (tests)
   
   ```
   Test suites 
   Suite 1-
          |- Test 1
          |- Test 2
   Suite 2-
          |- Test 1
   ```
   
   instead of current suite representation
   
   ```
   Test suites 
   Suite1 : Test1
   Suite2 : Test1
   Suite1 : Test2 
   ```
4. Show multiple instances of the same executed test case as a tree. If the TestNg Suite parallel flag is set to “methods” all the methods of the same suite are executed in multiple threads so each instance of the same test can be presented in any order and mix with other executed test cases,  this grouping assure that all the instances of the same test case are grouped together. (Multiple instances of the same test are executed when data-provider is used by the given test method or when invocationCount property is provided for the given method)
   
   ```
   Test cases
   Method 1  
          |- Method 1 [Tom, 34]
          |- Method 1 [Maria, 25]
          |- Method 1 [Dmitri, 40]
   Method 3
   Method 2
   ```
   
   Instead  of current behaviour
   
   ```
   Test cases    
   Method 1 [Tom, 34]
   Method 3
   Method 1 [Maria, 25]
   Method 2
   Method 1 [Dmitri, 40]
   ```
5. There is a need to label test method with the class it belongs to or optionally group the methods by their class. In TestNg Test there is an option to mix multiple methods from multiple classes so potentially methods names can be identical in several different classes and in current Allure report it's impossible to guess which method from which class was executed. Here is an example testNg.xml to demonstrate this situation: 
   
   ```
   <?xml version="1.0" encoding="UTF-8"?><!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >
   
   <suite name="Suite1" verbose="1" parallel="tests">  
   
       <test name="Test1">
           <classes>
   
               <class name="my.test.FirstTest">
                   <methods>
                       <include name="common" />
                       <include name="first" />
                   </methods>
               </class>
   
               <class name="my.test.SecondTest">
                   <methods>
                       <include name="common" />
                       <include name="second" />
                   </methods>
               </class>
   
           </classes>
       </test>
   
   </suite>
   ```

**Comment by baev** [comment]
1. Ok
2. Summon @just-boris 
3. Ok. No need to change model, you can just add `Suite`, `Group`, and `Test` labels, then you need to write custom tab plugin with such grouping
4. See 3. You can implement your own view for TestNG

**Comment by braimanm** [comment]
It’s better to change the model because currently I have to do a lot of tricks in TestNg adaptor to support simulation of real suite, the TestNg adaptor will be much cleaner if we introduce real suite representation. Currently there are a lot of workarounds in the TestNg Allure Listener.

Here how it will work in TestNg Allure Listener if we will change the model by adding SubSuites or Tests

onStart (Suite) 	– fire TestSuiteStartedEvent
onStart(Test) 		– fire new TestSubSuiteStartedEvent
onTestStart(Method) 	– fire TestCaseStartedEvent
onTestSkipped(Method) 	– fire TestCaseCanceledEvent + TestCaseFinishedEvent
onTestFailure(Method) 	– fire TestCaseFailureEvent + TestCaseFinishedEvent
onConfigurationSkip 	– fire TestCaseStartedEvent + TestCaseCanceledEvent + TestCaseFinishedEvent (will work for all configuration methods)
onConfigurationFailure 	– fire TestCaseStartedEvent + TestCaseFailureEvent + TestCaseFinishedEvent (will work for all configuration methods)
onFinish(Test) –fire new TestSubSuiteFinishedEvent
onFinish(Suite) – fire TestSuiteFinishedEvent (writes xml file)


And here how it works now:
onStart (Suite)  - i can't use this events as i have no context yet and no way to determine what will be the name of the simulated suite (Suite + Test) have to do all the work in onStart(Test)
onStart(Test) 		- fire TestSuiteStartedEvent
onTestStart(Method) 	– fire TestCaseStartedEvent
onTestSkipped(Method) 	– fire TestCaseCanceledEvent + TestCaseFinishedEvent
onTestFailure(Method) 	– fire TestCaseFailureEvent + TestCaseFinishedEvent
onConfigurationSkip 	– fire TestCaseStartedEvent + TestCaseCanceledEvent + TestCaseFinishedEvent (will work for all configuration methods but not for AfterSuite there is additional handling for AfterSuite event as it triggered after the last TestNg Test was executed which is not possible currently to detect so i create another suite file just for this AfterSuite event and the Allure report generator merges this suite with existing one with the same suite name)
onConfigurationFailure – fire TestCaseStartedEvent + TestCaseFailureEvent + TestCaseFinishedEvent (the same issue as with onConfigurationSkip
onFinish(Test) 		- fire TestSuiteFinishedEvent (writes xml file and the AfterSuite event is not possible to add to this suite as the context of this suite is lost see onConfigurationSkip how to handle this situation)
onFinish(Suite) - i can't use this event as all the suites are already finished and all xml files are written during onFinish(Test) event

**Comment by braimanm** [comment]
@baev do we have already ability to create custom tab plugins ?

**Comment by baev** [comment]
we are going to remove suites from model, and provide all information about suites using labes. See #558

Yes, you can create custom tab plugin sine 1.4.12. There is no docs for plugin api, you can only see https://github.com/baev/allure-report-plugins

**Comment by sskorol** [comment]
@baev just fyi, raised a new issue https://github.com/baev/allure-report-plugins/issues/1 - seems like plugins are not compatible with new face

**Comment by RocketRaccoon** [comment]
Any activity on developing TestNG plugin? Faced with similar issues in current xUnit plugin and want to implement a new one. Just don't want to start developing of a second bicycle.

**Comment by sskorol** [comment]
@RocketRaccoon plugins system is broken in the current version. So only in Allure 2.0 we'll be able to do that. However, according to the following [issue](https://github.com/cbeust/testng/issues/1073), we'd need to create a separate adapter in a scope of testng first, and then - Allure plugin. :)

**Comment by RocketRaccoon** [comment]
@sskorol thanks for info. There are a lot of  work to do, would like to help where it's possible.

**Comment by baev** [comment]
done in new TestNG adaptor. https://github.com/allure-framework/allure-java

<img width="467" alt="screen shot 2017-03-01 at 16 31 15" src="https://cloud.githubusercontent.com/assets/2149631/23461903/da71d74e-fe9c-11e6-99ff-4720be2563cf.png">
