### ISSUE TITLE
Flaky tests

### ISSUE THREAD

**Issue by 7170** [allure-framework/allure1#611]
Hi,

I have tested Allure with Maven and Jenkins and I saw a little thing embarrassing, there is no feature for Flaky tests (or Flakes).

When I use the -Dsurefire.rerunFailingTestsCount=x option see https://maven.apache.org/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html , tests are all registered, not marked as "corrected" like in Junit report.

In Junit report a test that constantly fail is a fail and a test that succeed the first time is a success, a Flaky test is a test which failed at least one time and succeed when retrying.

I think the better way to implement it is to create in the HTML report a new tab named Flakes or Flaky or Corrected.
Can it be implemented ?

**Comment by vania-pooh** [comment]
In my opinion this is a test smell when your test result is not 100% reproducible, so I'm not sure whether we need this functionality. However if you provide us a reasonable example where this is really needed - then let's discuss.

**Comment by Fanch-** [comment]
It could be useful for us too, for example in **functional testing** there are some exterior elements very specific which can cause a test to fail : wi-fi not available during a short period, or when you are using external API which breaks during a few seconds (and you haven't the hand on it). 

It can also come from the test, when we forget a verification so it makes the test flaky, but in this case it would be nice to have the flaky category to easily identify these forgetting (we added video recording -video link with @Attachment-, so if the wi-fi breaks we instantaneously see it on video -> false negative).
 
It's a way to manage false negative. 90% of the time relaunch the test will succeed. The plugin is awesome so it could be nice to integrate the flaky category.

Actually, the rerun is not filtered by the plugin, a solution should be to identify the state of rerun tests, if it passes from failed to succeeded, add them to flaky category (and not shown in fail/success).

**Comment by 7170** [comment]
I totally agree with @Fanch- it's a new feature not a big modification. 
For all users that are not using the rerun option, nothing will change. But for us, it's a big improvement in readability of the Allure report.

**Comment by baev** [comment]
Seems like reasonable

**Comment by lanwen** [comment]
Think it linked with issue about historical changes in reports (miss the exact number).

**Comment by Fanch-** [comment]
For example Jenkins has a plugin : https://wiki.jenkins-ci.org/display/JENKINS/Flaky+Test+Handler+Plugin

**Comment by dsafar** [comment]
+1 to this feature.  @vania-pooh is not wrong that it may be a test smell when a test is flaky, but this feature would be helpful in detecting and fixing that exact scenario.

**Comment by m-willemsen** [comment]
+1, maybe create another type of testresult besides passed/failed/broken/pending/cancelled and call it, well... flaked :)

**Comment by romainlouvet** [comment]
+1

**Comment by azakordonets** [comment]
Yeah, i would love to have this feature as well. I could try to do a pull request, but without guidance and help i'll most probably fail because of experience lack

**Comment by dimand58** [comment]
+1

**Comment by buzdin** [comment]
+1

this is not about historical results, but for reruns of failing tests in a single test run.
retries is a common feature of test frameworks. So if test passes in 10 times, it still passes, but needs to be quarantined and improved, so it gives more stable results. It is important that Allure could identify flaky tests visually somehow.

**Comment by thasherwin** [comment]
+1

**Comment by tk8817** [comment]
+20 , but this is really me looking for a server / report manager for Allure. Something which Repauto (they demoed at SelenConf 2015) were trying to do.

**Comment by jdeff** [comment]
I'm excited to see some movement on this. I'd love to see this added as well.

**Comment by Fanch-** [comment]
Same !!! By the way how will you manage that? 

I guess there will be a flaky category, with some checks on test name and state, but will we have the possibility to ignore the flakes tests in the product defects ? (People might have different visions for that), maybe a product flakes ?

How to keep the success/fail state of a test along with the flaky one? I mean for example in the test suites view, how will you display it ? A flaky green and a flaky red ? Just wondering ! 

It wiIl be a great feature anyway :)

**Comment by thasherwin** [comment]
It would be a very nice feature indeed. Looking for for it.

**Comment by Fanch-** [comment]
:(

**Comment by baev** [comment]
Almost done in Allure2. It now displays flaky tests https://github.com/allure-framework/allure2/releases/tag/2.0-BETA4

Also Allure2 already supports `surefire.xml`, issue to support retryFailure/retryError for it https://github.com/allure-framework/allure2/issues/148

Other integrations and server reporting is coming soon
