### ISSUE TITLE
Add the ability to use other fields in names of @Step

### ISSUE THREAD

**Issue by n4me1ess** [allure-framework/allure1#635]
Add the ability to use other fields in names of @Step
eg. global variables, className

**Comment by lanwen** [comment]
Relates #387

**Comment by baev** [comment]
@lanwen I don't think we will get an extension point for #387 in nearest releases but this one can be easy solved

**Comment by baev** [comment]
will not be resolved in Allure 1. Moved to https://github.com/allure-framework/allure-java/issues/14
