### ISSUE TITLE
Link pieces of the graphs to their corresponding sections

### ISSUE THREAD

**Issue by imtiazhossain** [allure-framework/allure1#644]
Hello, can you please link pieces of the graphs to their corresponding sections? My teams want to be able to click on parts of the graph and see which tests they correspond to. Much appreciated. Attached is a screenshot of the graphs just in case you're not sure what I'm talking about. Thanks!

![capture](https://cloud.githubusercontent.com/assets/7926510/9144779/40f87948-3d1d-11e5-8d9e-b3bf8c958489.JPG)

**Comment by baev** [comment]
moved to Allure 2 https://github.com/allure-framework/allure2/issues/192
