### ISSUE TITLE
The problem is TestNG and finding steps error installed using soft asserts

### ISSUE THREAD

**Issue by LooMaclin** [allure-framework/allure1#700]
Hi. Got a question. Would it be possible to implement the support for TestNG into Allure reports in order to display the bugs fixed with the help of Soft-Asserts correctly? In my opinion right now it looks incorrectly because the errors are not binding to the steps in which they have occurred.
![2015-10-30 16-01-10](https://cloud.githubusercontent.com/assets/10957765/10845289/71808a68-7f28-11e5-97bd-0df2151e2f40.png)

**Comment by vania-pooh** [comment]
@LooMaclin we're not using TestNG so this would be faster to send a patch to TestNG adapter via PR.

**Comment by baev** [comment]
moved to https://github.com/allure-framework/allure-java/issues/19
