### ISSUE TITLE
Links for @Stories and @Features

### ISSUE THREAD

**Issue by piociek** [allure-framework/allure1#702]
Can we add links for `@Stories` in Allure report? It would be similar to `@Issues` and `@TestCaseId` annotations. We may use another variable like 'allure.stories.tracker.pattern' to define url patter it would be similar, to `@Issues` and `@TestCaseId` configuration).

These links would be very helpful to even further  customise report and provide traceability to test management systems.

**Comment by ctapobep** [comment]
Basically the suggestion is to modify `@Story` into this: 
`@Story(value = "Story Name will appear in Behaviour tab", storyId = "17263")`

Therefore we'll refer to the story in 2 places - in Behaviour tab and in the test case itself (in the same way we reference Issues).

**Comment by piociek** [comment]
If '@Story(value = "Story Name will appear in Behaviour tab", id = "17263")' is acceptable I can implement this feature and create PR.

**Comment by lanwen** [comment]
Why not to use `TestCaseId` for that? Or u have both tms and story management system?

**Comment by baev** [comment]
@piociek @ctapobep thanks for suggestion!

> If @Story(value = "Story Name will appear in Behaviour tab", id = "17263") is acceptable I can implement this feature and create PR.

There is few problems with the proposed solution: 

First of all we should decide how to specify few stories for test case. Probably we should create a new `@StoriesGroup(Story[] value)` annotation. In this case we should support both ways (the old `@Stories` and a new one). Also we can use `java.lang.annotation.Repeatable` for `@Story` (requires java 8+). 

The next problem is how the store stories in model. For now we are using labels. It looks like this:

```xml
...
<test-case>
    <name>myTest</name>
    ...
    <labels>
        <label name="story" value="first story"/>
        <label name="story" value="second story"/>
    </labels>
</test-case>
```

So we can't simply change the model to store id as well.

**Comment by baev** [comment]
> Why not to use TestCaseId for that? Or u have both tms and story management system?

In some cases TMS knows about stories, so I would be nice to link stories in the report with TMS ones.

**Comment by piociek** [comment]
Can we add another entry to 
```
    <xs:simpleType name="label-name">
        <xs:restriction base="xs:string">
            <xs:enumeration value="feature"/>
            <xs:enumeration value="story"/>
            ...
        </xs:restriction>
    </xs:simpleType>
``` 
in `https://github.com/allure-framework/allure-core/blob/master/allure-model/src/main/resources/allure.xsd` named `storyId` ?

Then we may add optional `id` parameter to `@Story` annotation and it will solve our problem.

**Comment by baev** [comment]
Almost done in Allure 2; so stay turned!

**Comment by baev** [comment]
We have changed the behaviours tab in the report. Now it looks like this:

![screen shot 2016-11-02 at 17 13 32](https://cloud.githubusercontent.com/assets/2149631/19932110/de0ffa5a-a11f-11e6-9480-6c3278466225.png)

What do you guys think?

**Comment by ctapobep** [comment]
But we already had this functionality - when you select a story, there is a list of tests in the right panel. At least that's how it works in the older versions. So from the perspective of links between stories/tests - it stays the same. 

As for the aesthetics I'm not sure if this one is better. I personally was okay with the previous layout.

**Comment by baev** [comment]
BTW Allure 2 was released. Our team decided to close the issue because of feature freeze. Please consider to reopen the issue for Allure 2 if the problem still exists

PS this can be done via https://github.com/allure-framework/allure2/issues/153 and https://github.com/allure-framework/allure2/issues/91
