### ISSUE TITLE
TestNG @AfterClass step injected as the 1st step of the following test case

### ISSUE THREAD

**Issue by dmlemeshko** [allure-framework/allure1#706]
Test suite consists of 3 test classes.

1st test class contains: @Test  @AfterClass

2nd test class contains: @BeforeClass @Test  @AfterClass

3rd test class contains: @BeforeClass @Test @AfterClass

Issue: allure report put step from @AfterClass of 1st test class as a first step of 2nd test class just before the step from @BeforeClass;
Step from @AfterClass of 2nd test class as a first step if 3rd test class. Step from @AfterClass of 3rd test class is missing.

Expected result: @Step from TestNG @AfterClass is injected at the end of the same test class where @AfterClass method is placed. (Same as it works for @BeforeClass) 

![image](https://cloud.githubusercontent.com/assets/10977896/11206415/0ca78604-8d20-11e5-90b3-4973bbd1d6c8.png)

Reproduced on Allure v 1.4.19

**Comment by baev** [comment]
@dmlemeshko thanks for suggestion. There is a lot of issues about TestNg. In few words - Allure doesn't support test class fixtures. 

You can see: https://github.com/allure-framework/allure-core/issues/517 and https://github.com/allure-framework/allure-core/issues/570

**Comment by rab2215** [comment]
Is there an ETA resolving this bug? Looks like it has been open for a year.

**Comment by baev** [comment]
We are working on a new TestNG adaptor that will fix that issue. You can track the work on https://github.com/allure-framework/allure2/issues/108

**Comment by baev** [comment]
fixed in new TestNG adaptor https://github.com/allure-framework/allure-java
