### ISSUE TITLE
Allow Step titles to render html

### ISSUE THREAD

**Issue by ehasenkamp** [allure-framework/allure1#708]
In some instances our test highlight actions by bolding the step title, for example

``` html
<b>Typed</b> foo on By.cssSelector: #user
```

When this is rendered for the report, the step name is exactly as shown above; the html tags are displayed in all their glory.  It would be good to allow html to be rendered in the step names so that it appears like this

**Typed** foo on By.cssSelector: #user

To be more specific on the use case, here is a snippet of code

``` java
public void someMethod(){
   String stepName = "<b>Typed</b> foo on By.cssSelector: #user";
   logStep(stepName);
}

@Step("{0}")
private void logStep(String stepName) {
}
```

**Comment by just-boris** [comment]
We can't allow arbitrary HTML in the step title, it will make our system so vulnerable. 
Which use-case for the feature do you have?

If it is just for styling purposes, we can consider to add markdown support, as we do for test case description.

**Comment by ehasenkamp** [comment]
I hadn't considered it as a potential vulnerability as I was assuming only
test authors would be pushing details to the report.  If that is the case,
using markup is a viable alternative.  Please keep in mind, I'm also trying
to see if I can replace our current flat reports with Allure.

The only tags that are in use for our Step names are <b> and <href>.  The
latter because there are no notions of handling attachments, so navigation
to screenshots and captured text files are performed through step names.

Thank you for considering it.

**Comment by just-boris** [comment]
summon @baev. 
Are you fine with it?

**Comment by just-boris** [comment]
Also somewhere here was an issue about supporting links in step titles. So it is looks like a popular use-case.

**Comment by baev** [comment]
I guess we can support markdown in steps titles. But you have to remember that Allure doesn't support multiline steps titles.

**Comment by dimand58** [comment]
Old PR https://github.com/allure-framework/allure-core/pull/340

**Comment by arpitgold** [comment]
:+1:

**Comment by dimand58** [comment]
@baev Will be implemented in 1.5.0 ? =)

**Comment by qantium** [comment]
It will be very usefull feature!

**Comment by just-boris** [comment]
we will come back to this after global redesign: #721

**Comment by BabyRoot** [comment]
As a temporary and fast solution, I suggest to add a @Description to the steps, with the same functionality for test-case.

**Comment by marty30** [comment]
I haven't tested this, but I think @Step should also support all html special characters, like &amp; or &nbsp;. Like I said, I am not sure if this works already, but it should be something to take into account.

**Comment by baev** [comment]
please reopen the issue in Allure 2 https://github.com/allure-framework/allure2/issues

**Comment by BabyRoot** [comment]
Make copy - https://github.com/allure-framework/allure2/issues/331
