### ISSUE TITLE
Screenshot is not attached to report but available in 'allure-results' folder

### ISSUE THREAD

**Issue by ayanmodak** [allure-framework/allure1#730]
I am able to capture the screenshot on test failure and it is getting stored in 'allure-results' folder. But after running "mvn site" command the attachment is not getting attached in the allure-maven-plugin.html. Here is my code. 

``` java
// The test case
public class AllurePracticeTest {
    @Inject
    FirefoxDriver d;
    @Test
    public void reportGoogleTest(ITestContext testContext) {
        d = new FirefoxDriver();
        testContext.setAttribute("WebDriver", this.d);
        System.out.println(testContext.getAttribute("WebDriver"));
        d.get("https://www.google.co.in/");
        d.findElement(By.name("q")).sendKeys("abcd");
        // captureScreenshot();
        throw new AssertionError();
    }
    @AfterMethod(alwaysRun = true)
    public void close(ITestResult testResult) {
        d.quit();
    }
}

// The TestNG listener class
public class ListenerClass extends TestListenerAdapter {
    @Attachment
    public byte[] captureScreenshot(WebDriver d) {
        return ((TakesScreenshot) d).getScreenshotAs(OutputType.BYTES);
    }
    @Override
    public void onTestFailure(ITestResult tr) {
        Object webDriverAttribute = tr.getTestContext().getAttribute("WebDriver");
        if (webDriverAttribute instanceof WebDriver) {
            System.out.println("Screesnshot captured for test case:" + tr.getMethod().getMethodName());
            captureScreenshot((WebDriver) webDriverAttribute);
        }
    }
}

```

Steps are used to run:
1. mvn clean test
It is running the test properly. After completion it is generating one xml and a screenshot file in 'allure-results' folder.
2. mvn site
after successful run it is generating reports under site folder.
3. Opening the allure-maven-plugin.html in browser. 
It is not showing the screenshot though the same screenshot file is available in site\allure-maven-plugin\data folder.

**Comment by vania-pooh** [comment]
Here's a working TestNG adapter: https://github.com/allure-framework/allure-core/blob/master/allure-testng-adaptor/src/main/java/ru/yandex/qatools/allure/testng/AllureTestListener.java
Here's a working JUnit adapter: https://github.com/allure-framework/allure-core/blob/master/allure-junit-adaptor/src/main/java/ru/yandex/qatools/allure/junit/AllureRunListener.java
Please take a look at their code and do respective Allure API calls.

**Comment by ayanmodak** [comment]
Thanks for your support. It got resolved when I added the listener class in the test case instead of in the xml. I don't have any clue  why xml configuration does not work.
The following code block worked properly and screenshot is attached to allure report.
@Listeners({ ListenerClass.class })
public class AllurePracticeTest {

**Comment by baev** [comment]
@ayanmodak there is some magic with testNg listeners - in case you specify the listener via `testng.xml` aspectJ doesn't work properly. So you can save attachments and add steps via listener configured in `tesng.xml`. In case you are configuring listeners via SPI, maven-surefire-plugin or `@Listeners` all works fine

**Comment by baev** [comment]
fixed in new TestNG adaptor https://github.com/allure-framework/allure-java

**Comment by dmorokov** [comment]
In what component and with which version this fix was pushed in the maven repository?

**Comment by baev** [comment]
`io.qameta.allure:allure-testng:2.0-BETA5`. Docs: https://docs.qameta.io/allure/2.0/#_testng

**Comment by baev** [comment]
also you need to use allure2 to generate the report https://github.com/allure-framework/allure2

**Comment by dmorokov** [comment]
Is it possible to pick up and publish to maven repository this bugfix in allure-testng-adaptor version 1.*?
This very undesirable, for my and many other projects, to move to the allure 2 beta version.

**Comment by baev** [comment]
> Is it possible to pick up and publish to maven repository this bugfix in allure-testng-adaptor version 1.*?

Nope, the new adaptor is completely different

**Comment by ASaunin** [comment]
> also you need to use allure2 to generate the report https://github.com/allure-framework/allure2

@baev I faced with report generation problem when using `https://docs.qameta.io/allure/2.0/#_testng`

```
<reporting>
    <excludeDefaults>true</excludeDefaults>
    <plugins>
        <plugin>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-maven-plugin</artifactId>
            <version>LATEST</version>
        </plugin>
    </plugins>
</reporting>
```
Command `mvn site` fails with error:
```
[INFO] --- maven-site-plugin:3.5.1:site (default-site) @ test-app ---
[INFO] configuring report plugin ru.yandex.qatools.allure:allure-maven-plugin:LATEST
[INFO] Relativizing decoration links with respect to localized project URL: http://maven.apache.org/test-app
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.2 skin.
[INFO] Skipped "Allure" report (allure-maven-plugin:LATEST:bulk), file "allure-maven-plugin.html" already exists for the English version.
[INFO] Generating "Allure" report               --- allure-maven-plugin:LATEST:report
[INFO] Generate Allure report (report) with version 2.0-BETA6
[WARNING] The POM for ru.yandex.qatools.allure:allure-bundle:jar:2.0-BETA6 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 24.833 s
[INFO] Finished at: 2017-05-17T12:49:43+03:00
[INFO] Final Memory: 49M/317M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.5.1:site (default-site) on project test-app: Error generating allure-maven-plugin:LATEST:report: Could not generate the report: Can't resolve one or more given artifacts [ru.yandex.qato
ols.allure:allure-bundle:jar:2.0-BETA6]: Failure to find ru.yandex.qatools.allure:allure-bundle:jar:2.0-BETA6 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has
 elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```
Do you know, how to fix reporting problem?

**Comment by eroshenkoam** [comment]
@ASaunin maven plugin is not ready yet. 
Im currently working on it here: https://github.com/allure-framework/allure-maven/issues/32

**Comment by ASaunin** [comment]
@eroshenkoam What timelines is it planned to implement this functionality?

**Comment by eroshenkoam** [comment]
@ASaunin i'll done it in the end of the week
