### ISSUE TITLE
[Java API] Improve Allure Event Listeners API

### ISSUE THREAD

**Issue by baev** [allure-framework/allure1#735]
Some thoughts:
- We should copy all objects before provide it to listeners. 
- I doubt that allure events is useful in listener. Maybe better to provide context? An example when a step has finished provide Step object instead StepFinishEvent
- Maybe we should not add before and after fixtures for all events (an example - provide after fixture for all start events and before for finish events) maybe not.
- There should be ability to change data in listeners (I guess it should be different mechanism called rules. Listeners - only get information about lifecycle, Rules - change context. For an example - add screenshot after each step).

**Comment by RocketRaccoon** [comment]
Hi, any updates on that topic?

**Comment by baev** [comment]
> Hi, any updates on that topic?

Nope. Do you have any ideas/suggestions?

**Comment by RocketRaccoon** [comment]
I came to this issue from topics about matching test log directly with test steps. [#515](https://github.com/allure-framework/allure-core/pull/515) and [#420](https://github.com/allure-framework/allure-core/issues/420), also [failed](http://stackoverflow.com/questions/36432009/allure-store-test-log-per-step-with-testng) to use `AllureStepListener`. My point is that we would like to adopt allure in huge testing framework (testng + rest-assured) and we have no ability to set `@Step` and `@Attachments` to all required method. Now we just collect whole log at the end of the test and patched rest-assured to create steps and save log on request and response. Mechanism of rules would be very useful e.g. it could provide changes/add content to every step, to current step, to last executed step - that is what we need to apply allure to existing testing framework.

**Comment by baev** [comment]
Will not be fixed
