### ISSUE TITLE
Slightly large text attachments are extremely slow to render

### ISSUE THREAD

**Issue by monkpit** [allure-framework/allure1#770]
I am experimenting with the Python adaptors for Allure, and so far I am very pleased!

I have noticed, however, that attaching a moderately sized log as a TEXT type takes very long to render in Chrome (49.0.2623.112) - but not in Firefox.

Steps to replicate this issue:

Create a test that will be flagged as a defect.
Create a text attachment on the defective test. The text should be a reasonably large string (mine is around 300kb).
Run the tests with allure output.
Generate the Allure report and run the server.
Using Chrome: open defects, open the defective test result, open the attachments, and click on the text attachment.

Result: the page will hang for several seconds (6-7seconds when I run the Chrome profiler) while rendering the text.

Expected behavior: If you do the same steps in Firefox (44.0.2), clicking on the text attachment displays without any noticeable lag.

When I was profiling the delay with the Chrome console, I noticed that during the delay there are no network requests being made at all, the entire delay comes from Angular / Javascript execution.

**Comment by baev** [comment]
@monkpit hi! Sorry for the delay! I'll take a look

**Comment by just-boris** [comment]
What the type of attachement? Probably, that was XML or JSON. We are using syntax highlight, which can slow down the page loading

**Comment by sseliverstov** [comment]
1.5 Mb XML:
<1 sec- fetch, ~6 sec render without highlighting,  ~8 sec render with highlight.

 I can set max size to fetch and highlight (same value for both cases, for example 200k ), but maybe it is not better decision.

@baev @just-boris any ideas? BTW 6 sec for render without highlight  so strange

**Comment by just-boris** [comment]
How long does it take to show this file in raw mode?
Also we need to check our code, that do not copy string with content many times

**Comment by sseliverstov** [comment]
1 sec for fetch and show content without dom loading. I played with direct link and dev tool in chrome

**Comment by baev** [comment]
moved to Allure 2 https://github.com/allure-framework/allure2/issues/150

**Comment by shreyashah** [comment]
How to see the syntax highlighted? Does this show color on the fail trace log?
In my report, i never see any highlights text in fail log attachment

**Comment by baev** [comment]
> How to see the syntax highlighted? Does this show color on the fail trace log?
> In my report, i never see any highlights text in fail log attachment

Allure uses hightlight.js for code attachments. See https://github.com/allure-framework/allure1/blob/master/allure-report-face/src/util/attachmentType.js#L16-L23
