### ISSUE TITLE
Issues links in defect sub-header

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure1#772]
Hi all. 
We are using Allure also for tracking bugs created for test results. In current version of allure we have to open defect links and then click to related test cases to find any linked issues. 

My suggestion is to add links as aggregation list from all related test cases to defect sub-header like this:
![untitled](https://cloud.githubusercontent.com/assets/17307409/14418074/45a8008c-ffee-11e5-81ce-82e85c7392be.png)
I think there will be not so many links as in most cases one unique defect is related to one linked issue.

**Comment by just-boris** [comment]
Defect is a common error for several test cases. Issue can be added for one test case. So, we have to merge issues from several test cases somehow.

@Bakanych how do you tag issues? You have the following issues in all of 436 test cases or it is just some of them?

**Comment by Bakanych** [comment]
@just-boris in our scenario we're trying to find | create bugs in our issue tracker (which is TFS) using defect message, thus for every test case linked to defect we are having same collection of issues. That's why I came up with idea to display issues for defect instead of test case.
Probably there can be other issue types related directly to test case, but I have no idea what kind :)

**Comment by baev** [comment]
Moved to Allure2 https://github.com/allure-framework/allure2/issues/152
