### ISSUE TITLE
Multiply test ids

### ISSUE THREAD

**Issue by Bakanych** [allure-framework/allure1#773]
Hi all,
Now allure model supports 1-1 test case - test id link. I think there can be cases when one auto test covers several manual test cases, especially in case of large integration tests. We and some of my other colleagues have such situation in their projects.

My suggestion is replace testid to collection, like for issues:
![untitled](https://cloud.githubusercontent.com/assets/17307409/14418577/4ec51ec6-fff2-11e5-83a7-b33d8b255a8c.png)

**Comment by volkovs** [comment]
Hi @Bakanych 

> I think there can be cases when one auto test covers several manual test cases, especially in case of large integration tests.

What is your scenario? If automated test fails you execute it manually?

I see several different potential issues here:

1. Automated and manual tests are mixed. IMO test definition in TMS should include execution scenario and type. So, the same scenario executed manually and automatically creates different test cases in TMS (at least they may have different execution cycles). You can easily create your own Allure adapter for manual tests to be reported together with automated tests report.

2. You mix test and requirements coverage. Test can't cover "several manual test cases". Test covers some features, stories or requirements. In that case there is still 1:1 mapping to your test in TMS, which maps 1:n to multiple requirements. We might think about adding links to requirements (if linking area of report is not too overloaded).

3. With single integration test you try to cover too many requirements. From Allure perspective that is OK (as discussed above you can have mapping to multiple requirements). But that will create issues when you try to clean up your testware and remove duplicating tests. There will be no clear indication in your TMS what exactly is testes by each test case.

Thoughts?

**Comment by Bakanych** [comment]
Hi @volkovs 
Thanks for your detailed answer. Honestly I agree with you for all 3 points, but real life can be different sometimes :)
Regarding our scenario:
we have test plans in TFS MTM written by manual QA team and now we're covering it by automated tests using TFS linked items. TFS allows to link one test method to one manual test case, but in the other hand you can link same test method to N manual test cases.  That's why we have situation with 1:N relationship. Our automated scenarios are written with DSL framework and consider a lot of steps, thus one test method with several steps can be linked to several manual test cases in TFS MTM. Allure report allows us to track that links and help manual QA team to chose test cases they can skip during test plan execution.

**Comment by volkovs** [comment]
Hi @Bakanych

My idea was that if TMS has splitted the test into several entities, it did it for a reason and that 1:N mapping could be fixed not only in Allure, but also in TMS (if that was a mistake in the first place).

But you have a good point with 1 automated tests : N manual tests relationship. I have also seen pattern of our users trying to use multiple Test IDs. I think Allure guys gonna implement it in future.

**Comment by Bakanych** [comment]
@volkovs, thanks so much. Will be waiting for this feature in one of the next versions.

**Comment by baev** [comment]
Hi there! Issue will be fixed in Allure 2 (we are working on it right now, so stay turned)

**Comment by baev** [comment]
Summon 
@hemanthsridhar
@thasherwin
@irushah

**Comment by hemanthsridhar** [comment]
@baev  will this for for @TestCaseId("{0}") as discussed in https://github.com/allure-framework/allure-core/issues/799. It will be extremely helpful. Same goes for description, issues annotations as well.

**Comment by baev** [comment]
moved to allure2 https://github.com/allure-framework/allure-java/issues/1

If some of you want this in allure1 you can submit a pull request.
