### ISSUE TITLE
Add option to filter by date

### ISSUE THREAD

**Issue by eransc** [allure-framework/allure1#787]
**Filter By Date**
If you don't clean the output folder holding the xml files, the generated report will not have an option to filter just the tests you would like to see, like last day and so on

This can be useful if you want to run scheduled tests against production to verify everything is working even after going live (and not as part of the build)

Other filters are missing as well , like filtering by parameters  or environment variables inside the test.

**Comment by baev** [comment]
@eransc thanks for suggestion! Just added to Allure 2 roadmap.

**Comment by baev** [comment]
moved to allure2 https://github.com/allure-framework/allure2/issues/60
