### ISSUE TITLE
Screenshots in allure during Failed

### ISSUE THREAD

**Issue by Pranab078** [allure-framework/allure1#795]
I used TestNG and Allure. The below code for the screenshots during Failure.I get the Screen shot even in the target folder buti don see any screen shots in the Allure.below is my code

@Step("ShutDown")
  @AfterMethod(description="Tear Down Process")
    public void ShutDown(ITestResult testResult,Method method) throws InterruptedException, Exception {
        String testName = method.getName();
            try{
               if(testResult.getStatus()==ITestResult.FAILURE)
               {
                   System.out.println(testResult.getStatus());
                   TestScreenShots(testName);////This will take into another Folder Specified.
                   screenshot(driver, testName);//This Screen shoot should appear in the Allure.
                }
            }

```
    catch(Exception e)
    {}
    finally{
    System.out.println("Test finished: " + testName);
    driver.quit();  
    }
    }
```

//With the Below method i get the Screen shot stored in the Target folder, but doesnot seems to be seen in the Allure,ie After clicking on the (@Step("ShutDown")) method in Allure
@Attachment(value="{1}", type="image/gif")
    public static byte[] screenshot(WebDriver driver, String name) {
        byte[] screenshot = ((TakesScreenshot) driver)
                .getScreenshotAs(OutputType.BYTES);

```
 return screenshot;
```

}

**Comment by simple-elf** [comment]
I found [this](http://stackoverflow.com/questions/28606521/allure-framework-testng-adapter-incorrectly-places-aftermethod-in-report):
> It's problem of TestNG adaptor. In our adaptor we use ITestListener listener and onTestSuccess, onTestFailure, onTestFailedButWithinSuccessPercentage and onTestSkipped methods to mark test as finished. But TestNG call the methods before @AfterMethod.

And [here](http://stackoverflow.com/questions/29108159/allure-reports-screenshots-are-added-to-wrong-reports-using-aftermethod) is workaround:
```java

public class BaseTest implements IHookable {

    @Override
    public void run(IHookCallBack callBack, ITestResult testResult) {

        callBack.runTestMethod(testResult);
        if (testResult.getThrowable() != null) {
            try {
                takeScreenShot(testResult.getMethod().getMethodName());
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }

    @Attachment(value = "Failure in method {0}", type = "image/png")
    private byte[] takeScreenShot(String methodName) throws IOException {
        return getWebDriver().getScreenshotAs(OutputType.BYTES);
    }
}
```
Please read both links very carefully. This Listener must be added to Test class like
`@Listeners({ BaseTest.class })`

I used this with Selenide (and add some changes) but it works well. Maybe later I add examples for TestNG + Allure + Selenium and TestNG + Allure + Selenide

_Please edit first post to show java code correctly, because now it's unreadable_

**Comment by simple-elf** [comment]
Summon @baev. Maybe we can add some FAQ for TestNG users? Because so many questions on stackoverflow and here on github about TestNG @After[Method;Suite;etc] annotation

**Comment by baev** [comment]
Fixed in Allure 2 and new TestNG adaptor https://github.com/allure-framework/allure-java
