### ISSUE TITLE
Pending tests are included into pass rate computation

### ISSUE THREAD

**Issue by sskorol** [allure-framework/allure1#811]
Version: allure-core-1.4.24.RC1

Do we really need to use Pending tests in a pass rate computation? I believe they just create noise in statistics.

![image](https://cloud.githubusercontent.com/assets/6638780/15629495/94e0356c-2522-11e6-9bdc-342ce8c5e5cd.png)

Besides that, they're included into total tests' count, like they were executed within provided test suite.

![image](https://cloud.githubusercontent.com/assets/6638780/15629528/62968862-2523-11e6-964e-a8309726fdd3.png)

However, sometimes it's useful to see pending tests as well. Maybe we could add some filtering to exclude disabled / not implemented tests from charts?

**Comment by tk8817** [comment]
This is really the responsibility of the test runner. In Cucumber for example, if you want a test fully ignored then you can use a tag and set cucumber to skip it. However, if a test is processed and results in a status of 'pending' even though it may not have been run, it has been touched / executed by the test runner.

**Comment by sskorol** [comment]
@tk8817 I see your point, but let's take a look at TestNG sample. First of all, `pending` tests are forcibly included on `AllureTestListener` level:

    @Override
    public void onStart(ITestContext iTestContext) {
        // ...
        addPendingMethods(iTestContext);
    }

Then we include them in report face as `total` stats:

    getChartData() {
        const {total} = this.options.statistic;
        // ...
    }

So technically above chart is not a `pass rate` representation anymore. Well, I'm ok to display disabled tests, but I beleive there should be an option to exclude them from `total` and re-render chart. The same filtering that we have for grids.

**Comment by lanwen** [comment]
Pending tests should be in stats because of its a tests that you've defined, but never runned. So you should remove them completely or enable.

**Comment by sskorol** [comment]
I don't understand your argument, to be honest. They should be included because they just exist?
If it's only a template test for functionality which is under development, why should I create noise in stats by reducing pass rate? Yes, sometimes it's useful to see how many tests aren't implemented yet, but it's absolutely useless for cases when you need to provide an accurate pass rate for management. If tests were not executed, we shouldn't include them in pass rate computations. That's why I suggested adding some filtering. Just to be able to display figures, which provide a real value for the team. No one cares how many tests are currently under development (except developers). But everyone cares about how many working tests (which were physically executed) vs failed tests we have.

**Comment by lanwen** [comment]
You can simply remove `@Test` annotation to hide tests that you not want to show in report. If you have such pending tests - they can't be interpret as passed - they maybe ignored because of bug, or because they falling constantly, so it not completely successful report if it has pending tests. 

Btw thanks for this question, we should think more about philosophy of the pending status. But current approach exists all the time.

**Comment by baev** [comment]
Fixed in Allure 2
