### ISSUE TITLE
Impossible to click on second attachment if it have same content with currently opened one.

### ISSUE THREAD

**Issue by CoHuK** [allure-framework/allure1#821]
How to reproduce:
1. Create 2 attachments with different names, but same content.

Actual result:
You can click only on first attachment.

Expected:
Clicking on both should be possible.

**Comment by just-boris** [comment]
@CoHuK what version of Allure and what test framework are you using.

@baev as I remember we had attachment name as hashsum of its content. Is it still so?

**Comment by CoHuK** [comment]
@just-boris 1.4.22

**Comment by just-boris** [comment]
@CoHuK what about test framework?

**Comment by CoHuK** [comment]
Cucumber + Ruby

**Comment by baev** [comment]
> I remember we had attachment name as hashsum of its content

It is true for Ruby adaptor.

**Comment by smecsia** [comment]
@baev You're probably right. The respective code [is here](https://github.com/allure-framework/allure-ruby-adaptor-api/blob/master/lib/allure-ruby-adaptor-api/builder.rb#L86). I believe we could easily solve the issue by generating the unique names for every `add_attachment` method...
@CoHuK But what's the sense of having the same attachment twice?

**Comment by baev** [comment]
> But what's the sense of having the same attachment twice?

IMHO it is fine to have the same attachment twice. We should be able to deal with it. BTW Allure 2 is able to handle such situation, so lets pretend that this issue already fixed.

@CoHuK Allure 2 beta is coming very soon, so stay turned

**Comment by baev** [comment]
should be fixed in Allure 2
