### ISSUE TITLE
Allure should not throw exception on zero test results

### ISSUE THREAD

**Issue by etki** [allure-framework/allure1#835]
Hi.

Currently Allure assumes that if no reports has been fed in, it should instantly halt ([link](https://github.com/allure-framework/allure-core/blob/91e05c3a2e467432f18ce1ed960e8dfc843a8ddd/allure-report-data/src/main/java/ru/yandex/qatools/allure/data/AllureReportGenerator.java#L56-L59)). However, i think that this is not what should be done by default, or, at least, be configurable. Imagine following scenario: person X (that's me) has tens of similar repositories (e.g. fancy microservices with same boilerplate) and tries to create identical CI pipeline for every of them. However, if a single project does not generate any of allure reports, pipeline for that project would fail, while it's not necessary that project _had to_ have xml report at this very moment, and, probably, it should have empty html with warnings about missing sources. In the current philosophy Allure may turn successful build into failed one, but, as i think, it should not do so; report generation is an auxiliary action that may be unpleasant to fail, but that does not affect the build itself.

**Comment by baev** [comment]
@etki hi! Thanks for the report

**Comment by baev** [comment]
Fixed in Allure 2
