### ISSUE TITLE
Unexpected word-wrap in Defects tab on Russian

### ISSUE THREAD

**Issue by simple-elf** [allure-framework/allure1#836]
In verison [1.4.24.RC2](https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.24.RC2) wher is unexpected word-wrap in Russian text on Defects tab.

It can be easy fixed with css parameter `white-space: nowrap`

It seems to be only for Chrome (and possible Chromium based browser). In Firefox works OK.
![2016-07-27 14 33 25 xos92](https://cloud.githubusercontent.com/assets/668395/17170809/2f638de2-5407-11e6-9568-804d7cfe1ef8.png)

**Comment by baev** [comment]
@simple-elf hi. Thanks for the report!

**Comment by simple-elf** [comment]
Also there is no translation of tab names in New Face (see screenshot). Is it planned feature?
Please add translation also to widget titles on overview tab
