### ISSUE TITLE
Test case name is not highlightable in the test cases table

### ISSUE THREAD

**Issue by slipwalker** [allure-framework/allure1#837]
Test case name is not highlightable in the test cases table on a version 1.4.24.RC2 (see new version screnshot). On the previous versions , it was possible to highlight it, then copy and do searching by it through whole project to find matching test (see old version screenshot). Or just copy test case name from test cases details. It was very useful. Could you please either add possibility highlight name or return test case name on the above of the test cases details table where it was before?

New version:
<img width="1176" alt="new_version" src="https://cloud.githubusercontent.com/assets/720677/17176085/c69f4f5a-5413-11e6-8c26-f529164e445d.png">

Old version:
<img width="878" alt="old_version" src="https://cloud.githubusercontent.com/assets/720677/17176117/e4548cc2-5413-11e6-9748-e2ac0b49c2c8.png">

**Comment by just-boris** [comment]
That was fixed by #826.
Can we make @baev new release here?

**Comment by baev** [comment]
done https://github.com/allure-framework/allure-core/releases/tag/allure-core-1.4.24.RC3

**Comment by slipwalker** [comment]
Hey guys. Thanks for the fast response. But, actually it is not what I mean. Your fix just make parseable title of test case, e.g. Test Case Title. It is good. But would be great to have also initial test method name, e.g. testMethodName. Let it be on test cases' details as it was on the previous versions. Thanks in advance.

**Comment by thasherwin** [comment]
Yes. Thats a good one. That way you can easily find the method that was executed in your project by searching for it. Please make sure that the copy paste functionality works. 

Thanks

**Comment by pareshkrc** [comment]
Sorry, I initially came across this defect but as subject was different, I ignored it.. and opened new defect to have testMethod Name in the report. Here is the new issue - https://github.com/allure-framework/allure1/issues/897.
