### ISSUE TITLE
Add supporting of target="_blank" for links in Description section

### ISSUE THREAD

**Issue by RocketRaccoon** [allure-framework/allure1#840]
Hi,

Currently links which are rendered as markdown in Description section will be opened in the same tab.  It would be nice to render them with target="_blank" parameter.

**Comment by just-boris** [comment]
Actually we are using markdown, but you can use some html-tags if you want
Have you tried to add plain HTML with specified target:
```
<a href="example.com" target="_blank">New Tab</a>
```

**Comment by RocketRaccoon** [comment]
Yes, it's not working in 1.4.23. "New Tab" will render as regular text.

**Comment by just-boris** [comment]
Then this is a question to @baev regarding our markdown processor settings.

**Comment by baev** [comment]
Allure suppress all the html in markdown https://github.com/allure-framework/allure-core/blob/master/allure-report-data/src/main/java/ru/yandex/qatools/allure/data/utils/TextUtils.java#L105

**Comment by RocketRaccoon** [comment]
Yeah, I know about supressing. Any suggestion how to handle descibed case without big changes?

**Comment by baev** [comment]
moved to Allure 2 https://github.com/allure-framework/allure2/issues/330
