### ISSUE TITLE
Canceled tests are marked to be `Without feature`

### ISSUE THREAD

**Issue by almozavr** [allure-framework/allure1#843]
### Scope
- TestNG runner;
- Feature is applied to test class;
- failed test and tests which depend on it in the same test class.
### Problem

Canceled tests (which are ignored due to failed dependency) are shown as `Without Feature`, failed test feature is shown correctly
### Solution

Show canceled tests under the feature applied to their class correctly.

**Comment by baev** [comment]
Should be fixed in new TestNG adaptor https://github.com/allure-framework/allure-java
