### ISSUE TITLE
Create @SubFeatures annotation support

### ISSUE THREAD

**Issue by rosariomgomez** [allure-framework/allure1#845]
Is it possible to add @SubFeatures in Allure report to group the tests? 
The functionality would be similar to @Features annotations, but allowing @Features to have several nested @Subfeatures tags.

This will be very helpful to organize the behaviors results tab when there are a lot of scenarios marked with the same Feature.

**Comment by sskorol** [comment]
@rosariomgomez it's possible :) But even if someone creates PR for that, it'll never be merged into 1.4.24 version due to the same reason, as https://github.com/allure-framework/allure-core/pull/831. In short, it'll affect core, and most likely lots of people would need to refactor their code to update annotations for thousands of tests. So we have to wait for at least Allure 2.0.

**Comment by vania-pooh** [comment]
@sskorol yes, this is because we guarantee full XML compatibility of all 1.4.x versions.

**Comment by rosariomgomez** [comment]
@sskorol @vania-pooh thanks for your reply. I understand the need to wait for a new full version to incorporate it (like 2.0). Is there an ETA for that release?

**Comment by vania-pooh** [comment]
Summon @baev.

**Comment by sskorol** [comment]
@rosariomgomez you can track Allure 2 [roadmap](https://github.com/allurefw/allure-report/wiki/Roadmap).

**Comment by baev** [comment]
Allure 2 now supports `epic` -> `feature` -> `story` grouping in behaviours tab (Gonna be available in new adaptors https://github.com/allure-framework/allure-java and Allure2-BETA6)

**Comment by matlev1** [comment]
Hi there, 
I try to use epic > feature > story, but no luck on that, I have io.qameta.allure dependency in my pom.xml and these annotations are ignored altogether. Tried so many combinations of versions, nothing works. Please help!

**Comment by matlev1** [comment]
Am looking for a way to have another level in behavior tab but this is what I can get. 
On my class lever I have @Features, and on my test method level I have stories title and test, this all works but now I need to add another Annotation which could encapsulate Features. Is there an easy way to do this, other than epic > feature > story which still probably gives you 3 collapsible items: just like I have now.
