### ISSUE TITLE
Multiple Test Case IDs as multiple Issues

### ISSUE THREAD

**Issue by pumano** [allure-framework/allure1#846]
Sometimes my method cover few test cases per test and I need possibility to add multiple test cases id. @Issues have multiple, but @TestCaseId not. Can you add it?

issue example:

```
@Issues({
    @Issue("MYISSUE-1"),
    @Issue("MYISSUE-2")
})
public void testSomething() {
     ...
}
```

test case id example:

```
@TestCaseId({
    @TestCaseId("TEST-1"),
    @TestCaseId("TEST-2")
})
public void testSomething() {
     ...
}
```

**Comment by sskorol** [comment]
@pumano duplicates https://github.com/allure-framework/allure-core/issues/773

**Comment by hemanthsridhar** [comment]
@sskorol  this feature will be added in the next release

**Comment by iravasylyk** [comment]
was it already added to  allure version
<aspectj.version>1.8.9</aspectj.version>
		<allure.version>1.4.24.RC3</allure.version>
		<allure.plugin.version>2.5</allure.plugin.version>
if not please provide me with version number where it is implemented

**Comment by baev** [comment]
moved to allure2 https://github.com/allure-framework/allure-java/issues/1

If some of you want this in allure1 you can submit a pull request.

**Comment by hemanthsridhar** [comment]
@baev  is allure 2 deployed to maven central?
