### ISSUE TITLE
Actual screenshot not showing up in the Allure Behaviors section

### ISSUE THREAD

**Issue by prashanth-sams** [allure-framework/allure1#850]
Actual screenshot not showing up in the Allure `Behaviors` section; and returns no image in it.

As seen in the below images, the actual image should be `33e..` but it displays `c61..`

[![enter image description here](http://i.stack.imgur.com/kEplM.png)](http://i.stack.imgur.com/kEplM.png)

[![enter image description here](http://i.stack.imgur.com/cRgjV.png)](http://i.stack.imgur.com/cRgjV.png)

**Comment by baev** [comment]
Hi! Could you please provide some steps to reproduce the problem. The sample project is really appreciated.

**Comment by prashanth-sams** [comment]
Added here
https://github.com/prashanth-sams/ProtractorReports

**Comment by just-boris** [comment]
Hello, I have checked out your repo and build the report from files from `allure-results` folder and that worked for me fine.

For information, I ran `mvn site` and then `mvn jetty:site`. After these steps I could see screenshots in the report.

**Comment by baev** [comment]
closed due to no response
