### ISSUE TITLE
Additional severity / issues filters on dashboard

### ISSUE THREAD

**Issue by kevanescence** [allure-framework/allure1#851]
Hi,

I mainly use `allure` (version 1.4.23.HOTFIX1) for the `severity` and `link to issue` features.
Thus, it would be great if the dashboard would provide:
- A filter on severity to easily see which tests marked as BLOCKER, CRITICAL fail ... (With the current version we only see a graph but there is no link to the failed tests)
- A filter to see all failed tests which are not linked to any issue (well the ideal would be not linked to any issue or issue is not open but it is surely out of scope)

Please let me know if you have any question :)

Regards

**Comment by baev** [comment]
Will not be fixed in allure 1.*. Moved to allure2 https://github.com/allure-framework/allure2/issues/94
