### ISSUE TITLE
Duplicated step shown in report when the method step contains an optional parameter

### ISSUE THREAD

**Issue by danieldatri** [allure-framework/allure1#853]
When a test is calling a @step whose method contain at least one optional parameter like this:

``` groovy
@Step("My method")
public void myMethod(String param1, String param2 = "defaultValue"){


}
```

The step is duplicated into the report like this:

<img width="677" alt="screen shot 2016-08-31 at 8 33 29 pm" src="https://cloud.githubusercontent.com/assets/6400379/18150067/aa7cc718-6fba-11e6-95e8-dabddd6807f8.png">
## Steps to reproduce

Clone the following repo an follow the instructions in Readme file.
https://github.com/danieldatri/allure-example/

**Comment by baev** [comment]
@danieldatri that is fine because groovy generates byte code with two methods `myMethod(String)` and `myMethod(String, String)`, first one calls the second one with `defaultValue` as a second parameter. And I don't know how we should deal with it
