### ISSUE TITLE
[Feature request] Generate badge graphics

### ISSUE THREAD

**Issue by arpit-nagar** [allure-framework/allure1#859]
It wold be cool if allure-core additionally generates badge graphics for **passed testcases**/  **total testcases**, like the following example. sample 
![https://img.shields.io/jenkins/t/https/jenkins.qa.ubuntu.com/precise-desktop-amd64_default.svg](https://img.shields.io/jenkins/t/https/jenkins.qa.ubuntu.com/precise-desktop-amd64_default.svg)
https://img.shields.io/jenkins/t/https/jenkins.qa.ubuntu.com/precise-desktop-amd64_default.svg

Use case: These graphic files could be uploaded somewhere (or directly hosted by the build server) so that they can be referenced e.g. in a GitHub README page.

Ideally these graphics are generated as SVG to have no problems with background colors / scaling.

**Comment by just-boris** [comment]
Well, maybe it makes more sense to display test count, not only the binary "Build passed/failed" as Travis provides.

But the thing is that there is nothing to do with Allure. 
First of all, you can create a new test listener for your testing framework and publish results separately.
As other solution, you can read xml-files generated by Allure and create a new build step, which will create this badge for you.

And finally, it can be an idea to Allure plugin. @baev can we write to file system within plugin code?

**Comment by baev** [comment]
moved to Allure2 https://github.com/allure-framework/allure2/issues/151
