### ISSUE TITLE
Attaching a tab delimited file

### ISSUE THREAD

**Issue by hemanthsridhar** [allure-framework/allure1#861]
Attaching a tab delimited file is displaying like this.
PFA for the tab delimited file sample and the screenshot.
<img width="644" alt="screen shot 2016-10-02 at 8 14 50 pm" src="https://cloud.githubusercontent.com/assets/13584014/19021344/eb0898da-88dc-11e6-8c4e-829ea82b0642.png">

[tabDelimited.txt](https://github.com/allure-framework/allure-core/files/505019/tabDelimited.txt)

**Comment by sseliverstov** [comment]
With right mime type it works perfectly:
@Attachment(value = "TSV file", type = "text/tab-separated-values")
<img width="579" alt="2017-02-05 22 22 23" src="https://cloud.githubusercontent.com/assets/19683904/22629095/5ff4d2ec-ebf9-11e6-8772-43d91036fca3.png">
Please, try it.

**Comment by hemanthsridhar** [comment]
Thank you
