### ISSUE TITLE
Multi lines issue.

### ISSUE THREAD

**Issue by kemuning** [allure-framework/allure1#870]
Hi,

It seems to me that when you have a multi lines in @Description or @Stories at the method level

```
@Description("This is method testSub() \n" + 
                 "Another line of the description")
@Stories({"1. User can sub two numbers \n",
              "2. This will do substruction \n" +
              "3. Among two numbers"} )   //multi line stories
public void testSub(){
    Assert.assertTrue("Result not equals to 4", 2 * 2 == 4);
}
```

the report will display in a straight one single line.

Is it possible to maintain the format ?

Thanks.

**Comment by Ge0** [comment]
Hello,

I have the same issue as @kemuning and I find it to be annoying. Would you consider working on it in the near future?

Thank you.

**Comment by Ge0** [comment]
Ok I submitted a patch here: https://github.com/allure-framework/allure1/pull/893

Works fine now.
