### ISSUE TITLE
Allow "Features" to be inherited

### ISSUE THREAD

**Issue by afelisatti** [allure-framework/allure1#874]
Right now, since the Features annotation is not annotated with the "@Inherited" annotation, one cannot take advantage of the fact that most features have a test superclass and must instead annotate each specific subclass. Would it be possible to add the annotation?

**Comment by baev** [comment]
@afelisatti nice call, should be done in 1.5.2

**Comment by baev** [comment]
fixed in Allure 2 adaptors. You can send us a pull request if you want to have this in Allure 1, but I recommend you to migrate to new adaptors. https://github.com/allure-framework/allure-java/issues

**Comment by afelisatti** [comment]
Hi, @baev. I'm not sure when we would migrate so I've opened a PR for Allure1. Thanks!
