### ISSUE TITLE
#!/usr/bin/env bash instead of #!/bin/bash in command line tool

### ISSUE THREAD

**Issue by alexandermomot** [allure-framework/allure1#876]
Hello! The same issue here
https://github.com/allure-framework/allure-cli/issues/48
for the module
[allure-core/blob/master/allure-commandline/src/main/scripts/allure](https://github.com/allure-framework/allure-core/blob/master/allure-commandline/src/main/scripts/allure)

**Comment by baev** [comment]
fixed in allure2
