### ISSUE TITLE
Junit 5 support

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure1#877]
Hi,

Do you plan junit 5 support? if so when are you planning to release a beta version of allure for that?
I'm specifically interested in Dynamic tests available for Junit 5

Kind regrads

**Comment by ehborisov** [comment]
Hello @tnimni,

Allure 2 will have a Junit 5 adapter among the integrations, though before it will be fully implemented we want to introduce some changes in the junit 5 itself to make it suite us better. You can help us by up-voting the issue here https://github.com/junit-team/junit5/issues/618

**Comment by baev** [comment]
moved to allure 2 https://github.com/allure-framework/allure2/issues/110

**Comment by tnimni** [comment]
done, thanks!
@ehborisov
