### ISSUE TITLE
[Feature request] Test Run Overview should should include Stories/Features

### ISSUE THREAD

**Issue by macieklukasik88** [allure-framework/allure1#878]
Currently "Test Run" widget on the "Overview" tab is focused on number of total/passed/failed tests.

I think that nice to have would be two additional customer-focused metrics:

Features Passed - Percentage of features which have all cases passed.
Stories Passed - Percentage of stories which have all cases passed.

Regards,
Maciek

**Comment by baev** [comment]
this issue will not be fixed in allure 1.*. Moved to allure2 https://github.com/allure-framework/allure2/issues/92
