### ISSUE TITLE
[Feature request] Ability to add attachment at test-suite level

### ISSUE THREAD

**Issue by andye2004** [allure-framework/allure1#883]
Hi Guys, I'd love to have a way to do this; is there any plans to support it in the future?

The rationale for the question is that we can attach documents (HTML) at the suite level that convey information about the entire test suite, this way the information appears only once. At the moment we are having to attach documents at the test-case level meaning we are replicating the same information.

Many thanks, Andy.

**Comment by baev** [comment]
Allure 2 supports test fixtures, you will be able to make an attachment during set-up. In that case such attachment gonna be attached for all the test cases in the group. Unfortunately there is no way to support this in Allure 1.4.*

Allure 2 is pretty much ready for the release, now we working on updating integrations to support all the new features (the first adapters we gonna update is TestNG, JUnit and PyTest)

**Comment by andye2004** [comment]
Thanks @baev! I'll keep my eye open for Allure 2.

**Comment by baev** [comment]
@andye2004 what is your adapter btw?

**Comment by KroArtem** [comment]
@baev, can you please provide some ETA of Allure 2? We're planning to start using Allure in our projects. However, [Roadmap](https://github.com/allurefw/allure-report/wiki/Roadmap) seems to be a bit outdated and I'm not sure whether to wait for a new version or to start now. 

(Btw, our adapter is TestNG and it's needed to integrate with TeamCity (possibly Jenkins, that's an open question).)

**Comment by andye2004** [comment]
@baev We're using JUnit with the Allure JUnit adapter and a modified version of the Kirlionik cucumber adapter. Once the code for Allure 2 is available I can update our modified version of Kirlionik's adapter.

**Comment by wuhuizuo** [comment]
@baev 
Our team is using RSpec Framework, what's the date for supporting RSpec?
 Looking forward very much!

**Comment by vania-pooh** [comment]
@wuhuizuo probably I'm not correctly undestanding your question but general Rspec support is here: https://github.com/allure-framework/allure-rspec

**Comment by wuhuizuo** [comment]
@vania-pooh
I mean:suite attachments supportting in RSpec.

**Comment by baev** [comment]
Closing the issue as resolved. Related issues for adaptors:

RSpec https://github.com/allure-framework/allure-rspec/issues/76
JUnit https://github.com/allure-framework/allure-java/issues/12
