### ISSUE TITLE
Infinite Loading banner

### ISSUE THREAD

**Issue by ekonkov** [allure-framework/allure1#886]
Sometimes when report is opened there is only Loading banner spinning forever.

JavaScript console shows following:
```
TypeError: document.body is null[Learn More]  allure:71:21
	requests< https://********************************************************/allure/:71:21
	map self-hosted
	<anonymous> https://********************************************************/allure/:68:32
	.Deferred/d.then/</</< https://********************************************************/allure/webjars/jquery/2.1.1/jquery.min.js:2:28227
	n.Callbacks/j https://********************************************************/allure/webjars/jquery/2.1.1/jquery.min.js:2:26855
	n.Callbacks/k.fireWith https://********************************************************/allure/webjars/jquery/2.1.1/jquery.min.js:2:27673
	x https://********************************************************/allure/webjars/jquery/2.1.1/jquery.min.js:4:11118
	.send/b/< https://********************************************************/allure/webjars/jquery/2.1.1/jquery.min.js:4:14767
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.
```

Refresh fixes it.

Allure Version: 1.4.23
Platform: Ubuntu and Windows 7
Browser: FireFox 47.0.2 and 50.0.2

**Comment by baev** [comment]
Summon @just-boris

**Comment by just-boris** [comment]
This stack trace is from 1.4.x (angular-based) version.
I believe, that it will not happen with new UI.

**Comment by vania-pooh** [comment]
@just-boris any idea why this may happen? Guys are from Yandex.

**Comment by just-boris** [comment]
Related StackOverflow question: [Why is document.body null in my javascript](http://stackoverflow.com/questions/9916747/why-is-document-body-null-in-my-javascript).

In our case, Angular takes all responsibility to wait until the document is loaded. I have no any passion to dig deeper into this, as we have already rewritten everything
