### ISSUE TITLE
Get rid of external Maven dependencies

### ISSUE THREAD

**Issue by ctapobep** [allure-framework/allure1#891]
Right now Allure has a lot of dependencies that it brings into the project. Most Java libs try not to include any of the external dependencies since they may mess up the classpath. So usually there are 2 choices:

* Just get rid of the dependencies and write more of custom code
* Repackage the dependencies and include them into jar files with different package name

**Comment by vania-pooh** [comment]
The second approach really sucks IMHO. I think we could investigate how simple is to eliminate some Apache stuff from the project.

**Comment by lanwen** [comment]
What is that external dependencies? I see only `tika-core` (added not so far), jaxb-runtime and `properties-loader` (yep, its an old version with some legacy deps). This don't sounds like a "lot of".
So external deps count can be quickly reduced by upgrading property-loader.

Using shading for tika i think is a good idea.
