### ISSUE TITLE
Calculate HOST label only once

### ISSUE THREAD

**Issue by ctapobep** [allure-framework/allure1#892]
Right now in [AnnotationManager](https://github.com/allure-framework/allure1/blob/master/allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AnnotationManager.java#L176) the Host label is calculated on every test case. It tries to resolve a host name which is an access to DNS server (or cache).

This often is not a problem, but sometimes there are issues with DNS that could slow down the execution of that code. I experience such an issue right now and it takes approx 10sec to resolve the host name :)

BTW, is this HOST label really useful for people? Just curious.

**Comment by vania-pooh** [comment]
Yes, this is useful for runtimes executing tests on multiple hosts in parallel. E.g. in Yandex we have such runtime. This label is then used to show timeline by host in Allure.
