### ISSUE TITLE
Node JS: how to generate static html report using allure-results programmatically?

### ISSUE THREAD

**Issue by rahulmr** [allure-framework/allure1#896]
I have generated allure-results using wdio-allure-reporter which are number of json files and 1 suite xml file. Is there any report generator which can be used programmatically in NodeJS? Actually, I want to generate the reports in a single html file in the onComplete function of wdio.conf.js file. Preferably, do not want to use allure command line as it won't be platform independent.

Thanks in advance for providing a probable solution.

**Comment by vania-pooh** [comment]
1) Allure command-line is a Java application. It's platform independent.
2) You may want to use plugins for Jenkins, Teamcity or Bamboo.
3) Otherwise you need to implement Javascript report generation logic. It consists of two stages - converting XML files to Alluire JSON files and unpacking Allure face. Do you need more details about the process?

**Comment by just-boris** [comment]
@rahulmr have you tried to use https://www.npmjs.com/package/allure-commandline?

```
npm install allure-commandline
```

**Comment by rahulmr** [comment]
Yes, already tried but the problem it generates many folders and one html file. They should be serve through a web server. When I open the generated html file directly, the components are not loaded. Might be due to browser issue which is not supported that way of viewing the html file. Is it possible to get a single html file ?

**Comment by vania-pooh** [comment]
@rahulmr see http://stackoverflow.com/questions/23997449/allure-report-nothing-shown-in-chrome about not loaded JS.

**Comment by just-boris** [comment]
@rahulmr there is no any chance to see Allure without serving files somehow. 

This is foundational thing because our report is a single-page-app, that uses a lot of AJAX, which is not possible for static files.
