### ISSUE TITLE
Good to have Test Method Name & also Table Header should display Number of Passed/Failed/Broken/Canceled/Pending test (similar to old version report)

### ISSUE THREAD

**Issue by pareshkrc** [allure-framework/allure1#897]
We upgraded to 1.5.0 and observed that, in new report style we don't see test method name which we used to see (with copy to clipboard option) in previous version. 

It is useful and saves lots of time when we have many failures and want to search tests. 

Though test method names are split into component words to read as plain English, if we want to search any failed test, instead of typing we can simply use test method name.

Please find screenshots for the reference - 

**Old report:**
![image](https://cloud.githubusercontent.com/assets/18239333/21757556/9925429c-d5fe-11e6-8fd3-130fff54e741.png)

**New Report:**
![image](https://cloud.githubusercontent.com/assets/18239333/21757546/802f700a-d5fe-11e6-9e67-9d33de276051.png)

**One more observation:**
In previous report, we used to see "how many are passed/failed and so on from the Header, but in new report we don't have those numbers... 

**Previous version:**
![image](https://cloud.githubusercontent.com/assets/18239333/21757725/2a5a779e-d601-11e6-85e5-6bd8d135e5d2.png)
![image](https://cloud.githubusercontent.com/assets/18239333/21757755/5fca6268-d601-11e6-9090-840361e14d58.png)

**Latest version:**
![image](https://cloud.githubusercontent.com/assets/18239333/21757727/3a10375a-d601-11e6-82c7-79ffb9ae56ab.png)
![image](https://cloud.githubusercontent.com/assets/18239333/21757744/52fe7a60-d601-11e6-892e-df213fb5c05c.png)

Thanks!
Paresh

**Comment by pareshkrc** [comment]
We should supported result sorting by "Status", in latest report we don't have an ability to sorts results by "Status".

**Comment by sseliverstov** [comment]
#901

**Comment by pareshkrc** [comment]
thank you for having this in the report back!! :)

**Comment by pareshkrc** [comment]
This will be part of which version ?

**Comment by baev** [comment]
@pareshkrc you are welcome. 

> This will be part of which version ?

1.5.1 (I guess we will release it next week)

**Comment by pareshkrc** [comment]
Thanks! :)
