### ISSUE TITLE
Allure 2.11 update is not compatible with the version 2.10 of plugins jenkins job.

### ISSUE THREAD

**Issue by Nachiket26** [allure-framework/allure1#904]
My current jenkins version is : 2.32.1
Java version is : 1.8.0 Open JDK for the slave.

I had to apply some updates to Jenkins ant server. After that currently running UI Jobs started to fail because of report generation failure. It is a compatibility issue with an inbound Allure Jenkins plugin update.  

Currently I run version 2.10 of the "Allure Jenkins Plugin".   I installed update (2.11) which was available and installed but this turns out not to actually be compatible. The build is failing with following error :

ERROR: Build step failed with exception
java.lang.ClassCastException: [Lhudson.tools.ToolInstallation; cannot be cast to [Lru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation;
	at
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallations(AllureReportPublisherDescriptor.java:78)
	at
ru.yandex.qatools.allure.jenkins.AllureReportPublisherDescriptor.getCommandlineInstallation(AllureReportPublisherDescriptor.java:83)
	at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.getCommandline(AllureReportPublisher.java:188)
	at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.generateReport(AllureReportPublisher.java:160)
	at
ru.yandex.qatools.allure.jenkins.AllureReportPublisher.perform(AllureReportPublisher.java:90)
	at
hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at
hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at
hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at
hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
Build step 'Allure Report' marked build as failure

When the plugin is reverted back to 2.10, all is fine.

**Comment by baev** [comment]
see https://github.com/jenkinsci/allure-plugin/issues/75
