### ISSUE TITLE
v1.5 doesn't show time for step in report

### ISSUE THREAD

**Issue by tnimni** [allure-framework/allure1#907]
any way to show the time for step in report with this version?

it only show the time stamp at which the step started, in the previous version it also displayed the time per step (and it's sb steps)

Regards,

Tsachi

**Comment by choojoykin** [comment]
@baev sorry that I write here, but i didnt see changes in report. in page code i see divs with this commit.
google chrome latest version/firefox latest version
I can create a new report if u wish
![ya1](https://cloud.githubusercontent.com/assets/25221661/23377709/0f8b49c6-fd42-11e6-992a-519ca37a52a8.jpg)
![ya2](https://cloud.githubusercontent.com/assets/25221661/23377708/0f828958-fd42-11e6-92e9-d16e50ffd16c.jpg)

**Comment by just-boris** [comment]
At our demo report, it works. Try to put cursor over the time and you will see duration 

![image](https://cloud.githubusercontent.com/assets/812240/23378886/156582c4-fd35-11e6-91a6-c43f72d35603.png)

**Comment by choojoykin** [comment]
@just-boris yea, sry im expected this tooltip on my test step text. its ok now.
