### ISSUE TITLE
cannot set allure properties via surefire plugin

### ISSUE THREAD

**Issue by rab2215** [allure-framework/allure1#908]
When attempting to set allure properties via the surefire plugin, the system property value is not getting appended to the links for @TestCaseId annotations.

`<systemPropertyVariables>
<allure.tests.management.pattern>http://someUrl</allure.tests.management.pattern>
</systemPropertyVariables>`

When setting system property using surefire, i am able to print the defined value of the system property to the console during execution, so it is getting correctly defined.  I was able to successfully add it using an allure.properties file and with using command line arguments, just not using surefire as i would like.

**Comment by baev** [comment]
@rab2215 hi

`allure.tests.management.pattern` and `allure.issues.tracker.pattern` are the properties for generator. An example, if you are using maven plugin simply add them to the plugin configuration:

```xml
<configuration>
   <properties>
       <allure.issues.tracker.pattern>http://example.com/issues/%s</allure.issues.tracker.pattern>
       <allure.tests.management.pattern>http://example.com/tms/%s</allure.tests.management.pattern>
   </properties>
</configuration>
```
