### ISSUE TITLE
To customize my Allure report @Step and @Attachments are not working for TestNG in my local workspace. 

### ISSUE THREAD

**Issue by Peter2788** [allure-framework/allure1#909]
Hi All, 
I wanted to customize my alllure report by adding 3 more extra fields to the xml file(Report) which gets generated in local system.

@Step is not working.
I tried by adding @Step annotation at parameterized method. But content in the @Step annotation is not reflecting in the xml report.

When i searched in google for this query, many were telling to add AspectJWeaver dependency in the pom.xml.
But, my project is not maven project and i don't have pom.xml.
 In fact, i have aspectjweaver-1.8.9 jar in libraries.

Please guide me, is this configuration issue which i have to do to make @Step annotation work?

**Comment by baev** [comment]
@Peter2788 you need to specify weaver as `javaagent`

java -javaagent:aspectjweaver-1.8.9.jar ...

**Comment by Peter2788** [comment]
@baev Do i need to specify javaagent in build.xml?
As, <jvmarg value="-javaagent: ...\\aspectjweaver-1.8.9.jar -> For this i am getting "AspectJ Internal Error: unable to add stackmap attributes. null"
Reason:
   Expected stackmap frame at this location.
 Bytecode:
       0x0000000: 121e 4cb2 0019 2bb9 001f 0200 4d2c b900
       0x0000010: 2001 004e 2db9 0021 0100 3604 0336 0512
Note:  I have allure-testng-adaptor 1.4.16 version 

 Or in Run Configuration, Arguments field i have to pass?

**Comment by baev** [comment]
It depends on your build system and how did you run your tests.

> For this i am getting "AspectJ Internal Error: unable to add stackmap attributes. null

As far as I know this error means that something wrong with bytecode (old version of aspecj is used, classes are missed etc)

**Comment by Peter2788** [comment]
Thanks for your reply @baev .  It helped me :)
