### ISSUE TITLE
Insecure CSP settings recommended for Jenkins

### ISSUE THREAD

**Issue by malaikah** [allure-framework/allure1#910]
We use Jenkins in our build chain. Jenkins sits on a private network, with arbitrary access pretty heavily locked down. Jenkins itself, though, has access to some pretty sensitive things.

Our testers are keen to use Allure reports to report on build jobs, which are broken by the default CSP settings in Jenkins.

The Allure documentation does a good job of drawing attention to the work-around arrived at in the discussions around https://github.com/allure-framework/allure1/issues/715. This is probably acceptable in the short-term and its clear that the default Jenkins CSP need to be changed to allow javascript to be run from Jenkins itself. 

The CSP specification, seems to suggest that using unsafe-inline and unsafe-eval attributes should be discouraged.
See: http://www.w3.org/TR/CSP/#unsafe-hashed-attributes-usage

Are there any plans to make allure reports more safely compatible with CSP?

**Comment by just-boris** [comment]
Those two options, `unsafe-inline`, `unsafe-eval` for Angular-based version (prior to 1.4). As I see, latest version may work in more strict environment.

Unfortunately, at this time I don't have time to test and prove that statement. Maybe @baev can try to test this and update documentation if it just works.

**Comment by baev** [comment]
> Those two options, unsafe-inline, unsafe-eval were required for Angular-based version (prior to 1.4). As I see, latest version may work in more strict environment.

Yep, you right, latest version of the report requires more strict environment (almost all the unsafe rules)

> Are there any plans to make allure reports more safely compatible with CSP?

As far as I know since version 2.11 of Jenkins plugin it works fine with default CSP

**Comment by malaikah** [comment]
Thanks for responding so quickIy. Your comments now make me think I am doing something wrong, rather than hitting an unresolved issue. I wonder if you would help me work out what that is?

I'm a little confused about versions and whether this is where I should be seeking help for this here, or whether it would be more more appropriate to be logging an issue in https://github.com/allure-framework/allure2 or in https://github.com/jenkinsci/allure-plugin, so bare with me, if I am posting in the wrong place.

May I tell you a little more about the issue we seem to be seeing? Maybe you can offer some advice as to how I should proceed.

In a local test environment, I'm running Jenkins 2.43 on Centos 7.2.
I have the following plugins installed:
Resource Disposer Plugin (resource-disposer): 0.6
Pipeline: Stage View Plugin (pipeline-stage-view): 2.4
jQuery plugin (jquery): 1.11.2-0
Workspace Cleanup Plugin (ws-cleanup): 0.32
bouncycastle API Plugin (bouncycastle-api): 2.16.0
Pipeline: REST API Plugin (pipeline-rest-api): 2.4
Display URL API (display-url-api): 1.0.1
Mailer Plugin (mailer): 1.19
Pipeline Graph Analysis Plugin (pipeline-graph-analysis): 1.3
Pipeline: Milestone Step (pipeline-milestone-step): 1.3
JavaScript GUI Lib: ACE Editor bundle plugin (ace-editor): 1.1
Ant Plugin (ant): 1.4
OWASP Markup Formatter Plugin (antisamy-markup-formatter): 1.5
Branch API Plugin (branch-api): 1.11.1
Folders Plugin (cloudbees-folder): 5.16
Credentials Plugin (credentials): 2.1.11
Durable Task Plugin (durable-task): 1.13
External Monitor Job Type Plugin (external-monitor-job): 1.7
Git plugin (git): 3.0.1
GitHub plugin (github): 1.25.1
GitHub Branch Source Plugin (github-branch-source): 1.10.1
GitHub API Plugin (github-api): 1.84
Git client plugin (git-client): 2.2.1
GIT server Plugin (git-server): 1.7
Javadoc Plugin (javadoc): 1.4
JavaScript GUI Lib: Handlebars bundle plugin (handlebars): 1.1.1
Icon Shim Plugin (icon-shim): 2.0.3
JUnit Plugin (junit): 1.19
JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) plugin (jquery-detached): 1.2.1
LDAP Plugin (ldap): 1.14
Matrix Project Plugin (matrix-project): 1.8
Matrix Authorization Strategy Plugin (matrix-auth): 1.4
JavaScript GUI Lib: Moment.js bundle plugin (momentjs): 1.1.1
PAM Authentication plugin (pam-auth): 1.3
Pipeline: Build Step (pipeline-build-step): 2.4
Pipeline: Input Step (pipeline-input-step): 2.5
Pipeline: Stage Step (pipeline-stage-step): 2.2
Plain Credentials Plugin (plain-credentials): 1.3
SSH Credentials Plugin (ssh-credentials): 1.13
SCM API Plugin (scm-api): 1.3
Script Security Plugin (script-security): 1.25
Structs Plugin (structs): 1.5
Token Macro Plugin (token-macro): 2.0
Windows Slaves Plugin (windows-slaves): 1.2
Pipeline: API (workflow-api): 2.8
Pipeline: Basic Steps (workflow-basic-steps): 2.3
Pipeline: Nodes and Processes (workflow-durable-task-step): 2.8
Pipeline: Groovy (workflow-cps): 2.24
Pipeline: Shared Groovy Libraries (workflow-cps-global-lib): 2.5
Pipeline: Multibranch (workflow-multibranch): 2.9.2
Pipeline: SCM Step (workflow-scm-step): 2.3
Pipeline: Step API (workflow-step-api): 2.7
Pipeline: Job (workflow-job): 2.9
Pipeline: Supporting APIs (workflow-support): 2.12
build timeout plugin (build-timeout): 1.18
Credentials Binding Plugin (credentials-binding): 1.10
Email Extension Plugin (email-ext): 2.54
SSH Slaves plugin (ssh-slaves): 1.13
Timestamper (timestamper): 1.8.8
Pipeline (workflow-aggregator): 2.4
Git Parameter Plug-In (git-parameter): 0.7.2
GitHub Authentication plugin (github-oauth): 0.25
GitHub Organization Folder Plugin (github-organization-folder): 1.5
NodeJS Plugin (nodejs): 0.2.1
xUnit plugin (xunit): 1.102
packer (packer): 1.4
Slack Notification Plugin (slack): 2.1
Terraform Plugin (terraform): 1.0.9
Allure Jenkins Plugin (allure-jenkins-plugin): 2.11
HTML Publisher plugin (htmlpublisher): 1.12

I've configured an Allure Commandline installation, after http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-Buildagentshaveconnectiontomavencentral.
The installation is called allure_1.5.0 and downloads the latest available version of the allure commandline. This latest version is 1.5.0.

I'm using Jenkins pipeline to manage jobs, rather than configuring them by hand.
On first investigation, it appeared that the allure plugin might work with pipeline jobs, as the pipeline-syntax snippet generator provides snippets for it.
I tried an entry in my Jenkins file like:
````
tool 'allure_1.5.0'
allure(
  [
    includeProperties: false, 
    jdk: '', 
    properties: [], 
    reportBuildPolicy: 'ALWAYS', 
    results: [[path: 'allure-results']]]
)
````
When trying to include this in a pipeline job I get:
````
java.io.IOException: Cannot run program "allure" (in directory "/var/lib/jenkins/workspace/WCP_wcp-core_feature_FC-509-PBZRJGRWEFCSYFYXX7IJXAJW3G3WR5V2AKD5KJ57BYITTPWPTRRQ/test/im-fabric-ui-automation-framework"): error=2, No such file or directory
````
I tried a few permutation of this kind of format with no success. In particular, referencing the alternative DSL format documented in http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-jobdslpluginJobDSLPlugin, I tried:
````
  allure(
    [
      includeProperties: false, 
      jdk: '', 
      commandline: 'allure_1.5.0',
      properties: [], 
      reportBuildPolicy: 'ALWAYS', 
      results: [[path: 'allure-results']]]
  )
````
That didn't help, though.

Looking through the github repo for the Jenkins plugin, I noted that https://github.com/jenkinsci/allure-plugin/issues/49 seems to suggest that the allure plugin does yet not fully support pipeline builds.

Modifying the approach, I switched to steps in my Jenkinsfile, like:
````
withEnv(["PATH+ALLURE=${tool 'allure_1.5.0'}/bin"]) {
  sh 'allure generate allure-results'
}
````
That successfully generates the allure-report directory.

Taking inspiration from https://github.com/jenkinsci/allure-plugin/issues/49, I then used the htmlpublisher plugin to publish the generated reports:
````
publishHTML(
  [
    allowMissing: false,
    alwaysLinkToLastBuild: false,
    keepAll: false,
    reportDir: 'allure-report',
    reportFiles: 'index.html',
    reportName: 'UI Interface Tests'
  ]
)
````
This makes the reports accessible in the Jenkins GUI, but displays only a spinning disk. A console debugger displays the following CSP errors:
````
Content Security Policy: Couldn't process unknown directive 'sandbox'
Content Security Policy: The page's settings blocked the loading of a resource at self ("default-src 'none'").
Content Security Policy: The page's settings blocked the loading of a resource at https://172.25.255.11/job/WCP/job/wcp-core/job/feature%252FFC-509/UI_Interface_Tests/app.js ("default-src 'none'").
````

Testing a variety of CSP settings, the only combination that I could find that allowed the page to served without errors was that documented in http://wiki.qatools.ru/display/AL/Allure+Jenkins+Plugin#AllureJenkinsPlugin-configure-securityConfigureJenkinsContentSecurity.

I’m not terribly concerned about relaxing the security on Jenkins, but I don’t wish to do so without good reason. Your comments on the issue I raised seem to suggest that this should no longer be an issue (in which case, maybe the documentation should be updated?).

I'm a little confused about versions here. Is 1.5.0 of the allure commandline the correct version to be using with version 2.11 of the Jenkins plugin?

Is the format of the end reports governed by the version of allure that is used to generate the report, or the version of allure that is used to produce the results that are compiled into the reports?
Looking at the automation framework used to run the tests that are being reported on, it's using the npm package:
````
"cucumberjs-allure-reporter": "^1.0.3",
````
This is the latest version of this package and says that it supports allure report 1.4.15.
cucumberjs-allure-reporter is using v1.2.0 of allure-js-commons, which is recent, but not the latest version of this package.

Is there something else I should be doing?
Should I be asking for help somewhere else?

Regards,

Ben Priestman
