### ISSUE TITLE
No allure report generated if allure.issues.tracker.pattern contains percent mark

### ISSUE THREAD

**Issue by jaheikki** [allure-framework/allure1#916]
Allure report generating fails if 'allure.issues.tracker.pattern' url contains '%'-mark, that is not meant to use for substituting. Compare to '%s' which is used to substituting the key from the annotation. I consider this is a bug, since there can be special characters like '%'-mark in the url.

For example following url fails:
allure.issues.tracker.pattern=http://github.com/allure-framework/%20/allure-core/issues/%s

[INFO] Generate Allure report to /myPath/target/site/allure-maven-plugin
[INFO] Found results directory /myPath/target/allure-results
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.480 s
[INFO] Finished at: 2017-02-05T18:07:05+02:00
[INFO] Final Memory: 44M/552M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project my-project: Error during page generation: Error rendering Maven report: Could not generate the report: InvocationTargetException: ModelMapper mapping errors:
[ERROR] 
[ERROR] 1) Converter ru.yandex.qatools.allure.data.converters.DefaultTestCaseConverter$TestCaseResultProcessor@59313495 failed to convert ru.yandex.qatools.allure.model.TestCaseResult to ru.yandex.qatools.allure.data.AllureTestCase.
[ERROR] 
[ERROR] 1 error: Conversion = '2'
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by baev** [comment]
To escape `%`, you will need to double it up: `%%`
