### ISSUE TITLE
Requirements and free link additions to test case annotations

### ISSUE THREAD

**Issue by jaheikki** [allure-framework/allure1#918]
Now that there's possibility to use annotations to make links from the allure report to issue tracker system or link to system having testcase descriptions. But as far as I have understood there is no such option to link system requirements (from requirements tool) to the testcase report. Also it would be useful to add any free format links to testcase report.

As a reference see existing annotation features:
https://github.com/allure-framework/allure1/wiki/Issues
https://github.com/allure-framework/allure1/wiki/Test-Case-ID

I propose to add following features to the Allure report:
- "Requirement annotation" (see example below) + corresponding "pattern" to allure.properties.
- "Link annotation" to enable free format links added to allure report (see example below).

Example of the required new annotations (issue&testcase id exist already) to BDD style test:

"Feature: MyFeature

  @SeverityLevel.BLOCKER
  @Issue("Bug0001")
  @Issue("Bug0002")
  @TestCaseId("MyTest1")
  @Requirement("MyReq1")
  @Requirement("MyReq2")
  @Link("https://cucumber.io/docs/reference/jvm")
  @Link("https://github.com/allure-framework/allure-cucumberjvm")
  Scenario: Test scenario1
    Given myPreconditions
    When user does things
    Then do something"

**Comment by baev** [comment]
Allure 2 supports custom links

**Comment by jaheikki** [comment]
@baev Two questions:
1. When the Allure 2 will be available?
2. I'm using 'allure-maven-plugin' to generate the Allure report, so do I need to wait release > 2.5 of allure-maven-plugin to be able to get new releases of Allure frontend, regardless if it is new release 1.x or 2.0 of Allure? 
BR. Jari

**Comment by baev** [comment]
> When the Allure 2 will be available?

It depends on adaptor you are using. Our first priority are PyTest, TestNg and Jenkins/TeamCity/Bamboo integrations

> so do I need to wait release > 2.5 of allure-maven-plugin

Yep, current Maven integration isn't support Allure 2

**Comment by jaheikki** [comment]
@baev I'm using Allure Cucumber-JVM Adaptor v.1.6.1 and allure-maven-plugin  v.2.5. Please correct me if I'm wrong, are these the steps I need to wait to get Allure 2 UI officially?:
1. First Allure 2 release
2. New Cucumber-JVM Adaptor release having allure-2 dependencies included
3. New Allure Maven plugin release

**Comment by baev** [comment]
> I need to wait to get Allure 2 UI officially

Maven plugin update https://github.com/allure-framework/allure2/issues/49 . As far as Allure 2 supports old adaptors as well that is pretty much all.

**Comment by baev** [comment]
moved to https://github.com/allure-framework/allure-java/issues/1
