### ISSUE TITLE
Displaying Device ID

### ISSUE THREAD

**Issue by jalal-madden** [allure-framework/allure1#926]
Currently working with parallel_calabash & running multiple tests on each device outputting two xml files & then generating the html file. 
Although there doesn't seem to be any way to differentiate the tests as they both run the same tags. 
Would there be any way to display the Device ID so I can tell which device if failing?
Bare in mind I want to try stick with running it with parallel_calabash which restraints me to run each tag on each device.

**Comment by baev** [comment]
Good one, gonna be done in allure2, see https://github.com/allure-framework/allure2/issues/130
