### ISSUE TITLE
JS error when trying to see test details

### ISSUE THREAD

**Issue by marx-freedom** [allure-framework/allure1#927]
![allure-js-error](https://cloud.githubusercontent.com/assets/642092/22885524/e4227396-f20a-11e6-816e-c5e547edd4d7.png)

stack from console:

```
Uncaught TypeError: Cannot read property 'type' of undefined
    at Object.e.default (app.js:11)
    at Object.main (app.js:11)
    at n (app.js:8)
    at r (app.js:8)
    at Object.l (app.js:8)
    at Object.n [as invokePartial] (app.js:8)
    at 1 (app.js:11)
    at s (app.js:8)
    at n (app.js:8)
    at Object.<anonymous> (app.js:8)
```

We are using Allure 1.4.23.hotfix1 (same error with 1.5.1) , allure-maven-plugin 2.5 and junit adapter.
It's broken suddenly - a lot of old reports are correct.
Unfortunately I cannot attach complete report. 
Can I somehow disable minification of the app.js file?

**Comment by just-boris** [comment]
Seems like something is wrong with your `attachment.type`

Could you include an `xml` file for the `Task handler test`?

**Comment by marx-freedom** [comment]
XML file looks like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ns2:test-suite start="1486995678105" stop="1486996538379" version="1.5.1" xmlns:ns2="urn:model.allure.qatools.yandex.ru">
    <name>TaskHandlerTest</name>
    <test-cases>
        <test-case start="1486995678113" stop="1486995711334" status="passed">
            <name>test1</name>
            <steps/>
            <attachments>
                <attachment title="1-logs.zip" source="5c72bf06-3a95-443e-8260-6c7dc27a9b2a-attachment.zip" type="application/zip"/>
                <attachment title="2-logs.zip" source="123d1a08-b1be-41d8-9d56-9f2bf8ce92f0-attachment.zip" type="application/zip"/>
                <attachment title="3-logs.zip" source="359965bb-7a7d-473e-aeb1-5056e1819cab-attachment.zip" type="application/zip"/>
                <attachment title="4-logs.zip" source="de9595d4-2914-4b0d-a20f-b835a5184ea8-attachment.zip" type="application/zip"/>
                <attachment title="5-logs.zip" source="ffbc1a1b-eb1e-4df1-bac4-c06f265d3a80-attachment.zip" type="application/zip"/>
            </attachments>
            <labels>
                <label name="host" value="host-gt-lin-1"/>
                <label name="thread" value="15669@host-gt-lin-1.main(1)"/>
            </labels>
        </test-case>
    </test-cases>
    <labels>
        <label name="framework" value="JUnit"/>
        <label name="language" value="JAVA"/>
    </labels>
</ns2:test-suite>
```

All other test cases has the same content in the <attachements> tag (IDs are different, but content type is the same).

**Comment by slipwalker** [comment]
Yeah, I faced the same issue after Allure had been updated to 1.5.1 version. And everything is fine on 1.5.0 version. In my case it has been reproduced for FAILED tests only, there are no exclusive attachments just screenshot on failed test. If it matters, host url of my Allure report started from `https://`.

<img width="878" alt="error" src="https://cloud.githubusercontent.com/assets/720677/22933640/db33dc82-f2d4-11e6-99a3-961d9383c48a.png">

**Comment by marx-freedom** [comment]
Thank you for quick fix! Is there any plans to release 1.5.2?

**Comment by baev** [comment]
@marx-freedom done https://github.com/allure-framework/allure1/releases/tag/allure-core-1.5.2

**Comment by slipwalker** [comment]
When is it going to be available on maven central?
