### ISSUE TITLE
Screenshot after each step

### ISSUE THREAD

**Issue by yarafed** [allure-framework/allure1#936]
Config: Java+TestNG+Maven
Is it possible to make a screenshot after execution of each step(method with annotation @Step)?
Thanks in advance for your reply!

**Comment by sskorol** [comment]
Could be easily done with `aspectj`:

```java
@Aspect
public class ScreenshotsAspect {
	@After("execution(@ru.yandex.qatools.allure.annotations.Step * your.package..*.*(..))")
	public void takeScreenshotAfterStep(final JoinPoint joinPoint) {
		attachScreenshot("After " + joinPoint.getSignature().getName() + " screenshot");
	}
}
```

**Comment by yarafed** [comment]
@sskorol I've used this solution:
http://stackoverflow.com/questions/26030426/how-can-i-invoke-my-methods-before-and-after-mtd-annotated-by-step/26052783#26052783

Could you, please, tell me which solution is better?

**Comment by sskorol** [comment]
@yarafed just ask yourself if it's reasonable to call attachment method in each step explicitly?.. or would it be better to call it implicitly via aspect?

**Comment by yarafed** [comment]
@sskorol I am sorry, I didn't specify that I mean to use LifecycleListener. I totally agree with you that it will be not reasonable to call explicitly attachment method in each step, that's why I am trying to find a better solution.
