### ISSUE TITLE
ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255

### ISSUE THREAD

**Issue by abidrana7** [allure-framework/allure1#937]
Trying to generate the allure reports by ALLURE COMMAND LINE but got error as the followings:

[protracsol] $ "C:\Program Files (x86)\Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin\allure.bat" generate "D:\jenkins-workspace\workspace\protracsol\allure-results" -o "D:\jenkins-workspace\workspace\protracorsol\allure-report" \Jenkins\tools\ru.yandex.qatools.allure.jenkins.tools.AllureCommandlineInstallation\latest\bin.. was unexpected at this time. ERROR: Build step failed with exception ru.yandex.qatools.allure.jenkins.execption.AllurePluginException: Can not generate Allure Report, exit code: 255

**Comment by eroshenkoam** [comment]
Could you please move the issue to [allure-plugin](https://github.com/jenkinsci/allure-plugin/issues/new).

**Comment by abidrana7** [comment]
Moved!

**Comment by abidrana7** [comment]
This issue appeared because of Jenkins, when I used its windows installer version so I faced this issue. Once I uninstall the jenkins windows installer and then installed again jenkins.war this issue was resolved.
