### ISSUE TITLE
Graph feature: number of tests run not showing properly

### ISSUE THREAD

**Issue by danalbu** [allure-framework/allure1#938]
When running allure for a multi-configuration Jenkins job with 35 configurations we saw that the graph feature doesn't render the graphs correctly.
here are some screen-caps: http://imgur.com/a/RPUaZ 

I know this is only a cosmetic issue, but i just wanted to get the bug logged so you can track it or fix it in allure 2 :)

**Comment by baev** [comment]
@danalbu thanks for the report.

This is already fixed in Allure 2
