### ISSUE TITLE
 ConcurrentModificationException after success test

### ISSUE THREAD

**Issue by nemec8g** [allure-framework/allure1#940]
Hi all
I faced this issue on my framework based on java+groovy+ testNg + allure  allureVersion='1.4.24.RC3'

Allure crashes with ConcurrentModificationException and broke down testNg 
It happens with different number of tests in one class. Often it happends when test class has 1 test and parallel dataProvider

![screen shot 2017-02-16 at 11 21 32 am](https://cloud.githubusercontent.com/assets/25814391/23651721/76e55792-0337-11e7-94d5-876aff55920a.png)

**Comment by baev** [comment]
Please consider using Allure 2 adaptors instead https://github.com/allure-framework/allure-java
