### ISSUE TITLE
Add support to parameterized @Title annotation like in the @Step

### ISSUE THREAD

**Issue by Tigrenka** [allure-framework/allure1#945]
It would be good if we allow to use placeholders in the @Title like in the @Step
e.g.

```
@Title("Verify sending email to {0}")
```
will be rendered to
```
Verify sending email to test1@gmail.com
Verify sending email to test2@gmail.com
...
```
where test1@gmail.com, test2@gmail.com are the values of the first argument of the function.

**Comment by baev** [comment]
@Tigrenka sorry for the delay. 

In general I like this change, but I don't know how we will port this to Allure 2 adaptors since there are no more `@Title` annotation -- we are using build-in test titles instead (such as `@Test(description)` for TestNG and `@DisplayName` for JUnit 5)

**Comment by baev** [comment]
Closed because Allure 2 was released. Consider to reopen the issue in Allure2 https://github.com/allure-framework/allure-java
