### ISSUE TITLE
Implement adapter for Robot Framework (Jython)

### ISSUE THREAD

**Issue by Hamaoui-Issame** [allure-framework/allure1#947]
Hello,

I want to start developing an adapter for "robot framework" (Java Implementation).

I found this article: https://github.com/allure-framework/allure1/wiki/Creating-Allure-Adapter

Unfortunately it's not enough detailed.

Also, the [allure-java-commons](https://github.com/allure-framework/allure1/tree/master/allure-java-commons) module doesn't exist.

Any advises, or documents are welcome

Thanks you

**Comment by baev** [comment]
[allure-java]: https://github.com/allure-framework/allure-java
[allure-model]: https://github.com/allure-framework/allure2-model
[allure-lifecycle]: https://github.com/allure-framework/allure-java/blob/master/allure-java-commons/src/main/java/io/qameta/allure/AllureLifecycle.java
[gitter]: https://gitter.im/allure-framework/allure-core

Hello. It is makes sense to use allure2 model to implement a new adaptor. All you need is store `json` files during tests execution. You can find schema and some useful classes in [allure2-model][allure-model] repository, and example of usage in [allure-java][allure-java] repository. We are working on documentation, so there are no docs available for it for now, but it is pretty simple. 
The right way to generate the data is use [AllureLifecycle][allure-lifecycle]. The following code will create an simple passed test case and write it to `allure-results` folder.

```java
String uuid = UUID.randomUuid().toString();
Allure.getLifecycle().scheduleTestCase(new TestResult().withUuid(uuid).withName(name));
Allure.getLifecycle().startTestCase(uuid);
Allure.getLifecycle().updateTestCase(uuid, result -> result.withStatus(Status.PASSED));
Allure.getLifecycle().stopTestCase(uuid);
Allure.getLifecycle().writeTestCase(uuid);
```

You can use our [gitter room][gitter] to ask a more details during the work.
