### ISSUE TITLE
Not able to generate allure report file getting below eror along with this allure-maven-plugin.html screenshot

### ISSUE THREAD

**Issue by PratapSingh09** [allure-framework/allure1#949]
INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-site-plugin:3.3:site (default-site) @ Sample ---
[INFO] configuring report plugin ru.yandex.qatools.allure:allure-maven-plugin:2.5
[WARNING] No project URL defined - decoration links will not be relativized!
[INFO] Rendering site with org.apache.maven.skins:maven-default-skin:jar:1.0 skin.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Skipped "Allure" report, file "allure-maven-plugin.html" already exists for the English version.
[INFO] Generating "Allure" report    --- allure-maven-plugin:2.5
[INFO] Generate Allure report (aggregate) with version 1.5.2
[INFO] Generate Allure report to target/site/allure-report
[WARNING] Results directory for module Sample not found.
[WARNING] Allure report was skipped because there is no results directories found.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.864 s
[INFO] Finished at: 2017-04-04T12:31:50+02:00
[INFO] Final Memory: 20M/270M

```xml
 <modelVersion>4.0.0</modelVersion>
    <groupId>ru.yandex.allure</groupId>
    <artifactId>Sample</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <allure.version>1.5.2</allure.version>
        <allure.maven.version>2.5</allure.maven.version>
        <!-- Relative to the dir you're running from -->
        <allure.results_pattern>allure-results</allure.results_pattern>
    </properties>
    <dependencies>
        <dependency>
            <groupId>ru.yandex.qatools.allure</groupId>
            <artifactId>allure-report-face</artifactId>
            <version>${allure.version}</version>
            <type>war</type>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.eclipse.jetty</groupId>
                <artifactId>jetty-maven-plugin</artifactId>
                <version>9.2.10.v20150310</version>
                <configuration>
                    <webAppSourceDirectory>target/site/allure-maven-plugin</webAppSourceDirectory>
                    <stopKey>stop</stopKey>
                    <stopPort>2299</stopPort>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <reporting>
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>${allure.maven.version}</version>
               <!-- <reportSets>
                    <reportSet>
                        <reports>
                            <report>report</report>
                        </reports>
                    </reportSet>
                </reportSets>-->
                <configuration>
                    <resultsPattern>${allure.results_pattern}</resultsPattern>
                    <resultsDirectory>target/site/allure-results</resultsDirectory>
                    <reportDirectory>target/site/allure-report</reportDirectory>
                    <outputDirectory>${basedir}/site</outputDirectory>
                    <!--<reportVersion>1.4.15</reportVersion>-->
                </configuration>
            </plugin>
        </plugins>
    </reporting>
</project>
```

![image](https://cloud.githubusercontent.com/assets/17722170/24652989/411b728c-1934-11e7-9570-ed13153a1e0a.png)

**Comment by baev** [comment]
Your `allure-maven-plugin` configuration is wrong. See `allure-junit-example` for a complete example https://github.com/allure-examples/allure-junit-example/blob/master/pom.xml#L90-L99
