### ISSUE TITLE
Can't find allure commandline in Pipeline Jenkinsfile

### ISSUE THREAD

**Issue by tegarraharditya** [allure-framework/allure1#950]
Can't find allure commandline when using pipeline (Jenkinsfile), if we are using freestyle , (Post Build Step) it is no issue.

**Comment by baev** [comment]
@eroshenkoam am I right that the issue is fixed in 2.15?

**Comment by 9ah** [comment]
Hi, i am using the version 2.15 and I experience the same issue too - Can't find allure commandline <null>

**Comment by baev** [comment]
Could you please move the issue to https://github.com/jenkinsci/allure-plugin/issues
