### ISSUE TITLE
Demo report is down

### ISSUE THREAD

**Issue by Thibstars** [allure-framework/allure1#958]
The live demo report at http://ci.qatools.ru/job/allure1_master-deploy/lastSuccessfulBuild/Allure_report/ is down.
![image](https://cloud.githubusercontent.com/assets/6588019/26636456/29a11506-461d-11e7-9c83-62cb341f5173.png)

**Comment by baev** [comment]
Thanks, fixed. 

PS use https://ci.qameta.io/job/allure1/job/master/Allure_Report/ instead.
