### ISSUE TITLE
Allure - result folder not cleaned

### ISSUE THREAD

**Issue by PePeLM** [allure-framework/allure1#960]
Hello,
I have a strange behaviour running testng from Jenkins and generating result files- everything looks fine except that the allure result folder is not cleaned before next run? Is it a problem with my configuration or access rights to this folder or maybe something completly diffrent?

Part of my pom:
	
```
<properties>
		<aspectj.version>1.7.4</aspectj.version>
		<allure.version>1.5.3</allure.version>
	</properties>
```

	<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.9.8</version>
			<scope>test</scope>
		</dependency>

Jenkins ver. 2.46.3
Allure Jenkins Plugin 2.18

Thanks for hints,
Pawel

**Comment by PePeLM** [comment]
Ok, i found out the problem it was my pom config and maven goal in jenkins.

**Comment by sseliverstov** [comment]
@PePeLM, do you know that we have next version?  Source https://github.com/allure-framework/allure2, docs: https://docs.qameta.io/allure/latest/. Try it!

**Comment by PePeLM** [comment]
@sseliverstov, when it will be available in maven central repo?

**Comment by eroshenkoam** [comment]
You need to configure testng integration like here: 
https://github.com/allure-examples/allure-testng-example/blob/master/pom.xml

**Comment by eroshenkoam** [comment]
```
    <dependencies>
        ...
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>2.0-BETA8</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
```

**Comment by eroshenkoam** [comment]
```
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18.1</version>
                <configuration>
                    <testFailureIgnore>true</testFailureIgnore>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.aspectj</groupId>
                        <artifactId>aspectjweaver</artifactId>
                        <version>${aspectj.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
```
