### ISSUE TITLE
Duration time axis shown with repetitive time values

### ISSUE THREAD

**Issue by braimanm** [allure-framework/allure1#961]
To reproduce this issue create a test with extended execution time near 2 minutes and examine the duration chart. 
![image](https://user-images.githubusercontent.com/7651167/27541287-6233a418-5a51-11e7-9035-919907edb268.png)

**Comment by baev** [comment]
As far as I know the issue should be fixed in Allure 2. Can you check it out?

**Comment by braimanm** [comment]
Unfortunately I'm not using Allure 2 yet. Once I'll have a time I'll do it.

**Comment by baev** [comment]
Allure 2 fully supports data generated by old adaptors and brings more features to the report. That is pretty simple to upgrade, all you need is replace old Allure command line with a new one

**Comment by braimanm** [comment]
I'm not using command line in my framework I'm generating Allure report using report generation API. But I'll try to generate report using Allure 2 command line.

**Comment by baev** [comment]
BTW it would be so nice if you give us more details about your setup. I mean what is the reason of using Java API to generate report, are you using custom CI server or there is no integration available for your framework etc

**Comment by braimanm** [comment]
@baev the same problem exists on Allure 2
![image](https://user-images.githubusercontent.com/7651167/27543096-290e9750-5a57-11e7-89db-3c650c7c4ba3.png)

**Comment by baev** [comment]
could you please create an issue for allure2 as well?

**Comment by braimanm** [comment]
Yes

**Comment by braimanm** [comment]
About the reason for using API. My testing solution is packaged in single executable jar file which is running on VM instances which are created and disposed on demand. VM supports only Java run-time so all I'm doing is including your "allure-bundle" package to generate report, I found it much easier this way

**Comment by braimanm** [comment]
As for CI the job are executed from Jenkins and IO is collected through SSH from VM's at the end of the execution report is pushed from each VM to Jenkins slave using sftp

**Comment by baev** [comment]
Why not use Allure Jenkins plugin in that case? You can specify allure results folder using system property and generate the report using Jenkins plugin.

**Comment by braimanm** [comment]
We can't install plugins on Jenkins it's handled by other department. So i'm using HTML Publisher Plugin which is already installed on the Jenkins
