### ISSUE TITLE
[ERROR] Input directory should be not absolute for aggregate goal - TestNg,Maven,IDEA

### ISSUE THREAD

**Issue by tratseuskaya** [allure-framework/allure1#965]
Hello!
Allur-results directory is not generated.
**[ERROR] Input directory should be not absolute for aggregate goal.
[WARNING] Allure report was skipped because there is no results directories found.**

running from terminal - mvn clean site test
Target/site is generated
pom.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>FinalTask</groupId>
    <artifactId>FinalTask</artifactId>
    <version>1.0-SNAPSHOT</version>
        
            
            
            
        
        <properties>
            <java.version>1.8</java.version>
            <allure.version>1.4.16</allure.version>
            <aspectj.version>1.8.5</aspectj.version>
        </properties>
        <name>FinalTask</name>
        <description>FinalTask</description>
        <dependencies>
            <dependency>
                <groupId>io.qameta.allure</groupId>
                <artifactId>allure-testng</artifactId>
                <version>2.0-BETA16</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.hamcrest</groupId>
                <artifactId>hamcrest-all</artifactId>
                <version>1.3</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>1.7.21</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.testng</groupId>
                <artifactId>testng</artifactId>
                <version>6.11</version>
            </dependency>
            <dependency>
                <groupId>org.seleniumhq.selenium</groupId>
                <artifactId>selenium-java</artifactId>
                <version>3.4.0</version>
            </dependency>
            <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.16</version>
            <scope>provided</scope>
            </dependency>
            
            <dependency>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.6</version>
            </dependency>
        </dependencies>
        <build>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.18.1</version>
                    <configuration>
                        <testFailureIgnore>true</testFailureIgnore>
                        <argLine>
                            -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                        </argLine>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.aspectj</groupId>
                            <artifactId>aspectjweaver</artifactId>
                            <version>${aspectj.version}</version>
                        </dependency>
                    </dependencies>
                </plugin>
            </plugins>
        </build>
        <reporting>
            
            
                
                    
                    
                    
                
            
        
    
        <excludeDefaults>true</excludeDefaults>
        <plugins>
            <plugin>
                <groupId>ru.yandex.qatools.allure</groupId>
                <artifactId>allure-maven-plugin</artifactId>
                <version>2.6</version>
                <configuration>
                    <resultsDirectory>${project.build.directory}/target/allure-results/</resultsDirectory>
                    <inputDirectories>${project.build.directory}/target/allure-results/</inputDirectories>
                    <reportDirectory>${project.build.directory}/target/allure-reports/</reportDirectory>
                    <reportingOutputDirectory>${project.build.directory}/target/allure-reports/</reportingOutputDirectory>
                    
                </configuration>
            </plugin>
        </plugins>
            
    </reporting>
    </project>`

[screenshot](http://prntscr.com/g3ayi5)
Please help to solve the problem!
Thanks!

**Comment by savtambe** [comment]
Hi baev,
I am also facing the same issue. Please help

**Comment by baev** [comment]
@savtambe please consider using Allure 2 instead

**Comment by savtambe** [comment]
Hi @baev,
With below cloned project from git, i am able to generate the allure reports.
https://github.com/allure-examples/allure-testng-example

When i am creating maven project with TestNG with same pom i am getting below error.

[WARNING]  Results directory for module projectname tests not found.

[WARNING] Allure report was skipped because there is no results directories found

Is any other configuration required apart from pom?

**Comment by eroshenkoam** [comment]
@savtambe could you crate issue [here](https://github.com/allure-framework/allure2/issues/) and I will help you
