### ISSUE TITLE
How to show Red icon in Allure report, say when some test cases steps are failing

### ISSUE THREAD

**Issue by chethanshetty09** [allure-framework/allure1#967]
We can use the below code to Write logs to Allure report for Appium framework.
```
 @Step("{0}")
    public void log(final String message) {
        //Kept empty Intentionally
      
    }
```
This will print the message in allure as i want. Now suppose there is some fail test steps and i want to represent them in my allure report. How can i do that?

When some line throws Exceptions then allure will say test case failed which is fine, but i need a single step to be show as failed.

**Comment by baev** [comment]
```java
public void log(final String message, final Status status) {
    Allure.getLifecycle().fire(new StepStartedEvent().withName(name));
    Allure.getLifecycle().fire(new StepEvent() {
        @Override
        public void process(Step step) {
            step.setStatus(status);
        }
    });
    Allure.getLifecycle().fire(new StepFinishedEvent());
}
```

**Comment by v-mmirza36** [comment]
for latest 2.50 the above code not working please help me on this
